### ISSUE TITLE
status pending after client.apply()

### ISSUE THREAD

**Issue by sulphuricacid** [feast-dev/feast#1090]
## Expected Behavior 
I am trying to deploy feast using docker compose in my local.
 on client.apply() status of feature set should be STATUS_READY and i should be able to ingest the data and  data should be loaded to gcp storage and
## Current Behavior
i have tried with my own data set without historical serving by doing docker compose up and i have successfully ingested the data and able to retrieve features as well 
but when im enabling historical serving (i have configured the gcp details, project id , dataset id and all) and trying for client.apply()
the status of features is forever in pending.
job_controller -  is pulling 2 jobs forever
## Steps to reproduce
i have followed the deployment doc 
in **serving/historical_serving.yml**
project id and dataset id
feast.stores.config.staging_location : gs://mybucket/primarystaging
docker-compose up 
in **jobcontroller/jobcontroller.yml**
feast.jobs.runners.options.tempLocation : gs://mybucket/primarystaging
### Specifications

- Version: v.0.0.7
- Platform: docker-compose, gcp
- Subsystem: local(ubuntu 18.04)

**Comment by woop** [comment]
@sulphuricacid can you please confirm which regions you have configured for BigQuery and GCS? Are you using Dataflow?

**Comment by sulphuricacid** [comment]
i have configured US(multiple regions) for storage and US for bigquery.
but i live in India though.
i have one doubt, when u said make sure u add a suffix and anthersuffix for **feast.stores.config.staging_location**
 in the docker compose deployment, do i need to create that suffix and anothersuffix named folders in GCP storage ?

i dont see any error logs in docker logs in all the containers. except for this error in feast_core_1 container
org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:297)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:217)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:80)
	at org.flywaydb.core.Flyway.execute(Flyway.java:438)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:149)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:65)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1109)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at feast.core.CoreApplication.main(CoreApplication.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.net.UnknownHostException: db
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.postgresql.core.PGStream.<init>(PGStream.java:81)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:93)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:197)
	... 45 more
2020-10-23 07:46:07.136  WARN 36a66d34943f --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database: The connection attempt failed.
-------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : The connection attempt failed.

2020-10-23 07:46:07.145  INFO 36a66d34943f --- [           main] o.a.c.c.StandardService                  : Stopping service [Tomcat]
2020-10-23 07:46:07.176  INFO 36a66d34943f --- [           main] ConditionEvaluationReportLoggingListener : 



please help me .... i have removed all the images and did a fresh docker-compose up 
still the same... when i configure in .env true for historical serving... its failing... i even tried kubernetes deployment ... still the same...

im thinking im making a mistake in configuration .. but i have followed exactly what was given in the deployment docs

![Screenshot from 2020-10-24 09-06-25](https://user-images.githubusercontent.com/23690084/97067150-5948e200-15d8-11eb-896a-073a23199466.png)
![Screenshot from 2020-10-24 09-06-35](https://user-images.githubusercontent.com/23690084/97067154-5d74ff80-15d8-11eb-9916-3f7a16cf990d.png)

**Comment by woop** [comment]
@sulphuricacid Looks like a problem with Feast Core. Can you try and provide your `Feast Core` docker compose config yaml?

**Comment by woop** [comment]
Is the Postgres Database in Docker Compose coming online? Can you connect to it?

**Comment by sulphuricacid** [comment]
yes, postgres is online, im able to telnet localhost 5432 successfully 

do u mean infra/docker-compose/core/core.yml ?

i though it might a gcp connection error and tried to connect the storage bucket and bigquery from local using gsutil and it was successful. i authenticated the service account using the key.json and it was also successful 

![Screenshot from 2020-10-28 10-32-47](https://user-images.githubusercontent.com/23690084/97393587-26b92500-1909-11eb-814e-688c984ee7e1.png)

**Comment by woop** [comment]
> i though it might a gcp connection error and tried to connect the storage bucket and bigquery from local using gsutil and it was successful. i authenticated the service account using the key.json and it was also successful

Are all of the pods online eventually, or does Core continue to restart?

**Comment by sulphuricacid** [comment]
none of the containers restarting. everything stays online

**Comment by sulphuricacid** [comment]
All these bugs are not happening in development branch. 
i checked out the v0.7 dev branch and working fine
