### ISSUE TITLE
password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by avaranovich** [feast-dev/feast#1141]
## Expected Behavior 
All pods start properly

## Current Behavior
in the postgres POD, i see the following in the logs
```
2020-11-05 16:00:05.155 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-11-05 16:00:05.155 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2020-11-05 16:00:05.160 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-11-05 16:00:05.172 GMT [205] LOG:  database system was shut down at 2020-11-05 16:00:04 GMT
2020-11-05 16:00:05.177 GMT [1] LOG:  database system is ready to accept connections
2020-11-05 16:00:33.148 GMT [233] FATAL:  password authentication failed for user "postgres"
```

feast-core also fails with the following in the log
```

2020-11-05 16:06:47.700 ERROR dev-feast-core-69867cc98d-vjkgw --- [           main] o.s.b.SpringApplication                  : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database: FATAL: password authentication failed for user "postgres"
----------------------------------------------------------------------------------------------------
SQL State  : 28P01
Error Code : 0
Message    : FATAL: password authentication failed for user "postgres"
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
```

## Steps to reproduce
install `helm install dev feast-charts/feast `

### Specifications

- Version: 0.8-SNAPSHOT

## Possible Solution
I checked and there is the following secret key created dev-postgresql

which should be picked by both PODs. But that does not seem to happen.

**Comment by oavdeev** [comment]
Any chance you did helm install/uninstall, then changed the password, then did another install? I've ran into a similar issue with the Postgres chart where the first password gets written to a persistent volume, PVC are not deleted by helm uninstall and then the old password get reused on the next install.

Does it help if you delete the PVCs manually and do another install?

**Comment by woop** [comment]
Yea, I am pretty sure what @oavdeev said is the problem. We've run into it before as well.
