### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by hudengjunai** [feast-dev/feast#1191]
## Expected Behavior 
succeed deploy the feast docker-compose and run the minimal example 
## Current Behavior
run the feast series server , but hang when run the minimal_riding_hall example
## Steps to reproduce
-  run docker-compose -u d  in my macos .
- docker ps will  show all the feast container. 
-  config the docker-proxy for my macos in order to visit the notebook from chrome.
- run the mininal-riding-hall notebook one by one.
- run the notebook command block job = client.get_historical_features 
- hanged when job.get_output_file_uri 

### Specifications

- Version:development
- Platform:macos docker
- Subsystem:

## Possible Solution
Is there any config or network problem in development branch?

**Comment by hudengjunai** [comment]
![image](https://user-images.githubusercontent.com/33210026/99950644-cf975a80-2db7-11eb-9001-677899e232f8.png)

**Comment by woop** [comment]
@hudengjunai, just to confirm: Are you running the notebook from within the docker compose environment or outside? How long did you wait for results to be returned?

**Comment by hudengjunai** [comment]
> @hudengjunai, just to confirm: Are you running the notebook from within the docker compose environment or outside? How long did you wait for results to be returned?

Thanks for your reply. I running the notebook within the docker compose envirionment. 
A monment ago, I check the runing logs and found the "hang" is cause because of jupyter_1 server downloading jar package very slow.

**Comment by hudengjunai** [comment]
![image](https://user-images.githubusercontent.com/33210026/100039598-817a6980-2e40-11eb-9c0c-f79362594548.png)

**Comment by hudengjunai** [comment]
Is there any way to quickly deploy a stable version of feast? Can It be simple deployed  On google cloud or aliyun cloud? I want to run a pipeline demo and judge whether use feast as a middleware as mlflow platform.

**Comment by woop** [comment]
> Is there any way to quickly deploy a stable version of feast? Can It be simple deployed On google cloud or aliyun cloud? I want to run a pipeline demo and judge whether use feast as a middleware as mlflow platform.

Have you tried https://docs.feast.dev/getting-started/install-feast/kubernetes-with-helm?

**Comment by woop** [comment]
> > @hudengjunai, just to confirm: Are you running the notebook from within the docker compose environment or outside? How long did you wait for results to be returned?
> 
> Thanks for your reply. I running the notebook within the docker compose envirionment.
> A monment ago, I check the runing logs and found the "hang" is cause because of jupyter_1 server downloading jar package very slow.

Is it possible that it's being blocked by a firewall?

**Comment by hudengjunai** [comment]
> > Is there any way to quickly deploy a stable version of feast? Can It be simple deployed On google cloud or aliyun cloud? I want to run a pipeline demo and judge whether use feast as a middleware as mlflow platform.
> 
> Have you tried https://docs.feast.dev/getting-started/install-feast/kubernetes-with-helm?

Yes,I have tried , and read all the docs in the project. the firewall is not blocked. 
But failed when running the minimal example notebook.  I'm trying to deploy this feature store system as well as reading the code. 
Recently I'm developing a CTR  ranking module in recommendation system. The ranking module typically has two part ,fetch the user/item feature and send to tf_serving to get scores .For example, after recall stage ,I got 1000 videos for one , then choose the top 10 user would like to see.  so the feature is 1 user feature and 1000 item feature. Data structure like this 
```
{
    UserFaeture use_featue ;  //user feature is a feature_set has about 80 features
    List<Itemfeature> item_feature_list; // each ItemFeature is a feature_set has 50 features.
} 
```
I have found Feast fulfill our request, But I'm wondering **whether this system have low latency when fetch item features from online_feature store**. for real-time recommendation system , we want to fetch all the 1000 items within each item has 100 features from kv-store to memory in no more than 20ms。

So I deploy one instance on my computer, But a lot of issues comes up. 


1. I install the kubctrl helm and run the helm install command as https://docs.feast.dev/getting-started/install-feast/kubernetes-with-helm shows. forward and expose the node port for visit    
2. I connect to the feast jupyter and run the minimal riding hall. On first lines it succeed, creat the Client and registered the feature entity and feature tables. But unfortunately, I failed to get historical features and online features.  

So I sort out some problem encounted and list following:
### 1. the $HOME/.feast/config file   
the notebook block code run well until the cleint.get_historical_features?  first it says 
```python
KeyError: 'historical_feature_output_location'
During handling of the above exception, another exception occurred:
```
After I set config like this ,it runs
```
jovyan@feast-release-feast-jupyter-86444477b7-qx7jr:~/.feast$ cat config
[general]
historical_feature_output_location = file:///home/jovyan/test_data/output
spark_staging_location = file:///home/jovyan/test_data/staging
```

### 2. Downloading a lot jar failed 
when run get.historical_features and output_file_uri = job.get_output_file_uri() the jupyter pod need to download a lot of jars.which is very slow and finally failed to download ,I'm trying to fix by modify the ivy2settings.xml. 
```
:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [download failed: com.google.cloud.spark#spark-bigquery-with-dependencies_2.12;0.17.3!spark-bigquery-with-dependencies_2.12.jar, download failed: org.apache.httpcomponents#httpclient;4.5.12!httpclient.jar, download fa
iled: com.fasterxml.jackson.core#jackson-core;2.11.0!jackson-core.jar(bundle)]
```

**Comment by woop** [comment]
Thanks for the detailed explanation @hudengjunai 

> But I'm wondering whether this system have low latency when fetch item features from online_feature store. for real-time recommendation system , we want to fetch all the 1000 items within each item has 100 features from kv-store to memory in no more than 20ms。

Yes, it can fulfill that request. Normally we comply with SLOs of around 10ms @99p and 150 entities (items). If you want to support 1000 items then you need to scale out your Redis Cluster and online serving layer.

> when run get.historical_features and output_file_uri = job.get_output_file_uri() the jupyter pod need to download a lot of jars.which is very slow and finally failed to download ,I'm trying to fix by modify the ivy2settings.xml.

If you are using the Helm installation, are you using a production Spark cluster like Dataproc or EMR? If you are planning to run this software in production you should be using Dataproc/EMR and an object store like GCS or S3. The Jupyter notebook that is provided is for demonstration purposes, and runs the code in local/sdk mode. In production you should be running the Feast Job Service, and making sure that the Feast client connects to the Job Service. Clients should not have to download jars.

Finally, I will be trying out the example today to make sure that it works.

**Comment by paravatha** [comment]
@woop FYI, I ran into the same issue.
I updated ~/.feast/config as per @hudengjunai suggestion (thanks), it seems to be working.
I will dig deeper & play around with larger datasets.
**Newbie question: If I see the count increase on prometheus, does that mean my online serving working?**

<img width="1680" alt="Screen Shot 2021-01-07 at 10 12 39 PM" src="https://user-images.githubusercontent.com/8755869/103973885-2f627e80-5136-11eb-8fce-26758f2d8c01.png">

**Comment by paravatha** [comment]
nvm @woop, this seems like a health check request count

**Comment by ThrinathMphasis** [comment]
Hi woop,
i am not able to ingest data into the schema created.

client.ingest(driver_ft, ft_df)

**the Error :**



![error](https://user-images.githubusercontent.com/59553584/107468224-9b992d80-6b8d-11eb-9833-2c6846a5bb7a.PNG)
Removing temporary file(s)...
Traceback (most recent call last):
  File "original.py", line 347, in <module>
    client.ingest(salary_statistics, salary_stats_df)
  File "/home/ubuntu/feast_files/virtenv/lib/python3.6/site-packages/feast/client.py", line 937, in ingest
    file_url, with_partitions, dest_path, self._config
  File "/home/ubuntu/feast_files/virtenv/lib/python3.6/site-packages/feast/loaders/ingest.py", line 184, in _upload_to_file_source
    staging_client = get_staging_client(uri.scheme, config)
  File "/home/ubuntu/feast_files/virtenv/lib/python3.6/site-packages/feast/staging/storage_client.py", line 509, in get_staging_client
    return storage_clients[scheme](config)
KeyError: ''

**Comment by ThrinathMphasis** [comment]
Hi woop,
facing the same issue :
![erroe](https://user-images.githubusercontent.com/59553584/108825677-54795680-75e9-11eb-8ea3-83cb8e9962ab.PNG)

**Comment by woop** [comment]
Hi @ThrinathMphasis.

Can you please provide me with an exact description of 
* Which guide you are following
* Which system you are targeting (Minikube, GKE, Docker Compose)
* Which version of the Helm chart you are using
* Where you are running your commands (Jupyter notebook?)

I updated the latest Helm chart so you shouldn't be running into this problem any more, so it would be useful to know what your setup is.

**Comment by liuweibin6566396837** [comment]
> Hi @ThrinathMphasis.
> 
> Can you please provide me with an exact description of
> 
> * Which guide you are following
> * Which system you are targeting (Minikube, GKE, Docker Compose)
> * Which version of the Helm chart you are using
> * Where you are running your commands (Jupyter notebook?)
> 
> I updated the latest Helm chart so you shouldn't be running into this problem any more, so it would be useful to know what your setup is.
I met the same problem, when I use feast in my local k8s  (deployed by kubeadm). By thee way , I want to know if using feast without of google storage (Big Query need it?) possible?

**Comment by liuweibin6566396837** [comment]
@woop I met the same problem, when I use feast in local k8s(deployed by kubeadm).  
By the way, I wonder  handle my job by feast  without usage of `BigQuery Storage API`(big query connect need it?) possible?
