### ISSUE TITLE
Job fails after start , feast 0.8.0

### ISSUE THREAD

**Issue by Andrew32bit** [feast-dev/feast#1245]
Here is a log from jobcontroller:
`20/12/29 10:27:11 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 84284b7eec3c, 38539, None)
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/execution/streaming/ProcessingTimeTrigger
        at feast.ingestion.IngestionJob$.main(IngestionJob.scala:99)
        at feast.ingestion.IngestionJob.main(IngestionJob.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.execution.streaming.ProcessingTimeTrigger
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClas`

**Comment by Andrew32bit** [comment]
also it is not working on a furtger versions

**Comment by Andrew32bit** [comment]
It can be closed bcs - it was internet problems when jars were upload to jobcontroller
