### ISSUE TITLE
Feast CLI configuration fails

### ISSUE THREAD

**Issue by jpugliesi** [feast-dev/feast#1273]
## Expected Behavior 
I expect to be able to install and configure the feast CLI, [per the "Connect to Feast" docs](https://docs.feast.dev/getting-started/connect-to-feast/feast-cli)

## Current Behavior
invoking the feast CLI fails like so:
```
$ feast config set core_url feast-feast-core.feast-dev:6565
Traceback (most recent call last):
  File "/home/viaduct/.local/bin/feast", line 5, in <module>
    from feast.cli import cli
  File "/home/viaduct/.local/lib/python3.7/site-packages/feast/cli.py", line 29, in <module>
    from feast.job_service import start_job_service
  File "/home/viaduct/.local/lib/python3.7/site-packages/feast/job_service.py", line 47, in <module>
    from feast.third_party.grpc.health.v1 import HealthService_pb2_grpc
ModuleNotFoundError: No module named 'feast.third_party.grpc'
```

## Steps to reproduce
```
$ pip install  feast==0.8.2
...
Installing collected packages: feast
Successfully installed feast-0.8.2
$ feast config set core_url feast-feast-core.feast-dev:6565
Traceback (most recent call last):
  File "/home/viaduct/.local/bin/feast", line 5, in <module>
    from feast.cli import cli
  File "/home/viaduct/.local/lib/python3.7/site-packages/feast/cli.py", line 29, in <module>
    from feast.job_service import start_job_service
  File "/home/viaduct/.local/lib/python3.7/site-packages/feast/job_service.py", line 47, in <module>
    from feast.third_party.grpc.health.v1 import HealthService_pb2_grpc
ModuleNotFoundError: No module named 'feast.third_party.grpc'
```

### Specifications

- Version: 0.8.2

**Comment by woop** [comment]
Thanks for this @jpugliesi. I can confirm that the exact same issue happens for me when I run it locally.

**Comment by woop** [comment]
@jpugliesi can you confirm that it's working after the latest release?

**Comment by jpugliesi** [comment]
Can confirm this works with feast >=0.9 - thanks @woop !

**Comment by woop** [comment]
Awesome!
