### ISSUE TITLE
Feast offline to online Ingestion fails with java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by jpugliesi** [feast-dev/feast#1291]
## Expected Behavior
Running the `minimum_ride_hailing.ipynb` cell:
```
job = client.start_offline_to_online_ingestion(
    driver_statistics,
    datetime(2020, 10, 10),
    datetime(2020, 10, 20)
)
```

I expect this to ingest features to the online store

## Current Behavior
Running the cell with the EMR spark launcher and the default ingestion JAR fails with the following error:
```
Ivy Default Cache set to: /home/hadoop/.ivy2/cache
The jars for the packages stored in: /home/hadoop/.ivy2/jars
:: loading settings :: url = jar:file:/usr/lib/spark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.google.cloud.spark#spark-bigquery-with-dependencies_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-4758fce5-e100-4b21-95a4-f9c193d675a7;1.0
	confs: [default]
	found com.google.cloud.spark#spark-bigquery-with-dependencies_2.12;0.18.0 in central
:: resolution report :: resolve 112ms :: artifacts dl 2ms
	:: modules in use:
	com.google.cloud.spark#spark-bigquery-with-dependencies_2.12;0.18.0 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   1   |   0   |   0   |   0   ||   1   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-4758fce5-e100-4b21-95a4-f9c193d675a7
	confs: [default]
	0 artifacts copied, 1 already retrieved (0kB/5ms)
Exception in thread "main" java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
	at scopt.Head$.<init>(options.scala:148)
	at scopt.Head$.<clinit>(options.scala)
	at scopt.OptionParser.head(options.scala:251)
	at feast.ingestion.IngestionJob$$anon$1.<init>(IngestionJob.scala:34)
	at feast.ingestion.IngestionJob$.<init>(IngestionJob.scala:32)
	at feast.ingestion.IngestionJob$.<clinit>(IngestionJob.scala)
	at feast.ingestion.IngestionJob.main(IngestionJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:853)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:937)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
21/01/26 19:53:45 INFO ShutdownHookManager: Shutdown hook called
21/01/26 19:53:45 INFO ShutdownHookManager: Deleting directory /mnt/tmp/spark-4f76bc02-60fb-4d1b-b92f-40c45d76297c
Command exiting with ret '1'
```

## Steps to reproduce
```
pip install feast==0.9.0rc2
```
Run the minimal_ride_hailing.ipynb up to and including cell:
```
job = client.start_offline_to_online_ingestion(
    driver_statistics,
    datetime(2020, 10, 10),
    datetime(2020, 10, 20)
)
```

### Specifications

- Version: 0.9.0rc2
- Subsystem: EMR spark launcher

**Comment by jklegar** [comment]
Thanks @jpugliesi, closing this since it was resolved in the Feast Slack (thread for future reference here: https://kubeflow.slack.com/archives/CE0L8T267/p1611691595025300?thread_ts=1611346585.014800&cid=CE0L8T267) tl;dr Feast uses Scala 2.12 and this was being run on an EMR version that uses Scala 2.11

**Comment by woop** [comment]
@jpugliesi please let us know if your issue isn't resolved!
