### ISSUE TITLE
Online to Offline Ingestion Failing In Hello World Example Notebook

### ISSUE THREAD

**Issue by Gcav66** [feast-dev/feast#1421]
I'm running through the Hello World example. I can't complete the offline to online ingestion step. The pod logs indicate an issue connecting to Redis. 

## Expected Behavior 
The online ingestion job should complete
```
job = c.start_offline_to_online_ingestion(
    driver_info,
    dt.datetime(2020, 1, 1),
    dt.datetime(2020, 2, 1),
)

wait_for_job(job)
```
## Current Behavior
Right now the job just hangs and does not complete. When I look at the jupyter pod logs I see:
```
21/03/28 11:51:25 INFO FileSourceStrategy: Output Data Schema: struct<driver_id: bigint, name: string, surname: string, event_timestamp: timestamp ... 2 more fields>
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:59)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:288)
	at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:35)
	at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:72)
	at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:196)
	at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:320)
	at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:236)
	at com.redislabs.provider.redis.RedisConfig.<init>(RedisConfig.scala:135)
	at feast.ingestion.stores.redis.RedisSinkRelation.<init>(RedisSinkRelation.scala:56)
	at feast.ingestion.stores.redis.RedisRelationProvider.createRelation(DefaultSource.scala:34)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:175)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:213)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:210)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:171)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:122)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:121)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:963)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:100)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:160)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:87)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:963)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:415)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:399)
	at feast.ingestion.BatchPipeline$.createPipeline(BatchPipeline.scala:81)
	at feast.ingestion.IngestionJob$.main(IngestionJob.scala:104)
	at feast.ingestion.IngestionJob.main(IngestionJob.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to localhost:6379
	at redis.clients.jedis.Connection.connect(Connection.java:165)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:109)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1904)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:130)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:899)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	... 44 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:53)
	at redis.clients.jedis.Connection.connect(Connection.java:158)
	... 51 more
```
From within my notebook, I used netcat to verify I can reach Redis service using the service's IP and PORT and DNS
`!nc -zv feast-release-redis-master-0.feast-release-redis-headless.default.svc.cluster.local 6379` - both succeed.

 However, per the JedisConnectionException, I can't reach localhost 6379 

## Steps to reproduce
I followed the installation instructions for Kubernetes with Helm. I ran the notebook: feast-hello-world.ipynb
### Specifications

- Version: 
```
{'sdk': {'version': '0.1.dev0'},
 'serving': {'url': 'feast-release-feast-online-serving:6566',
  'version': 'v0.9.3'},
 'core': {'url': 'feast-release-feast-core:6565', 'version': 'v0.9.3'}}
```
- Platform: EKS
- Subsystem:

**Comment by woop** [comment]
Hey @Gcav66, thanks for filing this issue. 

Can you confirm that you are using PySpark as your launcher from within the notebook? I am assuming yes (that you didn't change to another Spark launcher like `Spark on K8s`).

Would you mind printing the output of 

```
print(c._config)
```
I want to see what you've configured your redis URL as. I'm assuming that it should be the cluster IP.

**Comment by Gcav66** [comment]
I am using the PySpark launcher. But, my mistake, I did not set the Redis URL.

```
[general]
project = default
core_url = localhost:6565
core_enable_ssl = False
enable_auth = False
core_server_ssl_cert = 
serving_url = localhost:6566
serving_enable_ssl = False
serving_server_ssl_cert = 
job_service_enable_ssl = False
job_service_server_ssl_cert = 
job_service_enable_control_loop = False
grpc_connection_timeout = 10
grpc_connection_timeout_apply = 600
batch_ingestion_production_timeout = 120
batch_feature_request_wait_time_seconds = 600
auth_provider = google
spark_ingestion_jar = https://storage.googleapis.com/feast-jobs/spark/ingestion/feast-ingestion-spark-develop.jar
spark_standalone_master = local[*]
dataproc_executor_instances = 2
dataproc_executor_cores = 2
dataproc_executor_memory = 2g
spark_k8s_namespace = default
spark_k8s_use_incluster_config = True
historical_feature_output_format = parquet
redis_host = localhost
redis_port = 6379
redis_ssl = False
statsd_enabled = False
deadletter_path = 
stencil_url = 
ingestion_drop_invalid_rows = False
telemetry = True
```

Setting `os.environ["FEAST_REDIS_HOST"] = <My Redis Cluster IP>` resolved my error.

Thank you for your help on this

**Comment by woop** [comment]
Cool, thanks!
