### ISSUE TITLE
Error during feast materialize-incremental: AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by qooba** [feast-dev/feast#1480]
## Expected Behavior 

It should be possible to materialize TableView if some values for some rows are None

## Current Behavior

In the current version error appears when any value in historical store is None.
On command:
```
feast materialize-incremental 2021-05-21T23:46:43
```

I have error:
```
Materializing feature view app_features from 2021-04-19 00:03:27.010110+00:00 to 2021-04-21 21:55:52+00:00Traceback (most recent call last):

  File "/opt/conda/bin/feast", line 8, in <module>

    sys.exit(cli())

  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__

    return self.main(*args, **kwargs)

  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main

    rv = self.invoke(ctx)

  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1259, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke

    return callback(*args, **kwargs)

  File "/opt/conda/lib/python3.8/site-packages/feast/cli.py", line 247, in materialize_incremental_command

    store.materialize_incremental(

  File "/opt/conda/lib/python3.8/site-packages/feast/feature_store.py", line 337, in materialize_incremental

    provider.materialize_single_feature_view(

  File "/opt/conda/lib/python3.8/site-packages/feast/infra/local.py", line 188, in materialize_single_feature_view

    rows_to_write = _convert_arrow_to_proto(table, feature_view, join_keys)

  File "/opt/conda/lib/python3.8/site-packages/feast/infra/provider.py", line 260, in _convert_arrow_to_proto

    value = python_value_to_proto_value(row[idx])

  File "/opt/conda/lib/python3.8/site-packages/feast/type_map.py", line 317, in python_value_to_proto_value

    value_type = python_type_to_feast_value_type("", value)

  File "/opt/conda/lib/python3.8/site-packages/feast/type_map.py", line 160, in python_type_to_feast_value_type

    return type_map[value.dtype.__str__()]

AttributeError: 'NoneType' object has no attribute 'dtype'
```

## Steps to reproduce

The error will appear for any input which contains None value in any row.

### Specifications

- Version: Feast SDK Version: "feast 0.10.0"
- Platform: Python
- Subsystem: Linux

## Possible Solution

We can use feature ValueType instead of parsing type from value if value is None

**Comment by woop** [comment]
Thanks for raising the issue and submitting a PR @qooba. I'll respond on the PR itself.
