### ISSUE TITLE
GCP Dataproc error during offline to online ingestion

### ISSUE THREAD

**Issue by horatiu-negutoiu** [feast-dev/feast#1484]
## Expected Behavior 

1. `start_offline_to_online_ingestion` spark job gets submitted.
2. job runs successfully.

## Current Behavior

1. `start_offline_to_online_ingestion` spark job gets submitted.
2. job fails with the error:

```
21/04/21 07:09:26 WARN org.apache.spark.SparkConf: The configuration key 'spark.yarn.user.classpath.first' has been deprecated as of Spark 1.3 and may be removed in the future. Please use spark.{driver,executor}.userClassPathFirst instead.
21/04/21 07:09:26 WARN org.apache.spark.SparkConf: The configuration key 'spark.yarn.user.classpath.first' has been deprecated as of Spark 1.3 and may be removed in the future. Please use spark.{driver,executor}.userClassPathFirst instead.
Exception in thread "main" java.lang.NoSuchMethodError: org.json4s.ShortTypeHints.<init>(Lscala/collection/immutable/List;)V
	at feast.ingestion.IngestionJob$.<init>(IngestionJob.scala:30)
	at feast.ingestion.IngestionJob$.<clinit>(IngestionJob.scala)
	at feast.ingestion.IngestionJob.main(IngestionJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1030)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

## Steps to reproduce

- deployed Feast in `GCP/GKE` using Helm chart. Tested deployment by connecting to it, creating feature tables, and retrieving feature tables (ie. not data, just the table 'object')
- when trying the offline to online ingestion, the Feast deployment reports that a Spark launcher is needed in order to perform that action. We chose Option 2 (Dataproc) as per documentation.
- deployed Dataproc cluster in `GCP/Dataproc/our-dataprod-cluster`.
- the offline to online ingestion job is submitted again. It submits successfully this time, without errors in the jupyter notebook. It appears in the `GCP/Dataproc/jobs` page but fails after 6-7 seconds with the error above.

![image](https://user-images.githubusercontent.com/19393629/115515441-1e57fc00-a253-11eb-908d-7e4a9a733dba.png)

### Specifications

- Version: 0.9.3
- Platform: GCP
- Subsystem: GKE + Dataproc

## Possible Solution

1. Specify a different set of JAR files?
2. Upgrade to 0.10 and see what happens?

**Comment by jklegar** [comment]
Hey @horatiu-negutoiu, thanks for trying out Feast! I believe this issue covers the same error: https://github.com/feast-dev/feast-spark/issues/42

**Comment by horatiu-negutoiu** [comment]
Thank you so much! Closing.
