### ISSUE TITLE
On Windows, `feast init` may result in an invalid repository

### ISSUE THREAD

**Issue by diogommartins** [feast-dev/feast#1551]
## Expected Behavior 

* `feast init` should generate an example with a valid `FileSource` path

## Current Behavior

```
(venv) C:\Users\diogo\PycharmProjects\stone\rex-data\feature-store\feature_repo>feast init demo_repo

Creating a new Feast repository in C:\Users\diogo\PycharmProjects\stone\rex-data\feature-store\feature_repo\demo_repo.


(venv) C:\Users\diogo\PycharmProjects\stone\rex-data\feature-store\feature_repo>cd demo_repo

(venv) C:\Users\diogo\PycharmProjects\stone\rex-data\feature-store\feature_repo\demo_repo>feast apply
Traceback (most recent call last):
  File "C:\Users\diogo\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\diogo\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\diogo\PycharmProjects\stone\rex-data\feature-store\venv\Scripts\feast.exe\__main__.py", line 7, in <module>
  File "c:\users\diogo\pycharmprojects\stone\rex-data\feature-store\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\diogo\pycharmprojects\stone\rex-data\feature-store\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\diogo\pycharmprojects\stone\rex-data\feature-store\venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\diogo\pycharmprojects\stone\rex-data\feature-store\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\diogo\pycharmprojects\stone\rex-data\feature-store\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\diogo\pycharmprojects\stone\rex-data\feature-store\venv\lib\site-packages\feast\cli.py", line 163, in apply_total_command
    apply_total(repo_config, Path.cwd())
  File "c:\users\diogo\pycharmprojects\stone\rex-data\feature-store\venv\lib\site-packages\feast\repo_operations.py", line 120, in apply_total
    repo = parse_repo(repo_path)
  File "c:\users\diogo\pycharmprojects\stone\rex-data\feature-store\venv\lib\site-packages\feast\repo_operations.py", line 93, in parse_repo
    module = importlib.import_module(module_path)
  File "C:\Users\diogo\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\diogo\PycharmProjects\stone\rex-data\feature-store\feature_repo\demo_repo\example.py", line 12
    path="C:\Users\diogo\PycharmProjects\stone\rex-data\feature-store\feature_repo\demo_repo\data\driver_stats.parquet",
         ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
 
```

## Steps to reproduce

`feast init` and `feast apply` on a filepath with folders that would result on a string with invalid escape sequences. E.g: `"C:\Users\diogo\PycharmProjects\stone\rex-data\feature-store\feature_repo\demo_repo\data\driver_stats.parquet"`

### Specifications

- Version: 0.10.3
- Platform: Windows 10

## Possible Solution

A possible fix is to always use `pathlib.Path.as_posix`, wich in this case, would result in `C:/Users/diogo/PycharmProjects/stone/rex-data/feature-store/demo_repo/data/direver_stats.parquet`. 

May I perform the changes and submit a pull request?

----

* https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.as_posix

**Comment by woop** [comment]
Hi @diogommartins!

Thanks for raising this issue. Unfortunately we've not explicitly developed for Windows nor tested it, and I don't think we can officially support windows, but if you want to take a stab at changing our code to unofficially support it, then feel free!

**Comment by diogommartins** [comment]
> Hi @diogommartins!
> 
> Thanks for raising this issue. Unfortunately we've not explicitly developed for Windows nor testing for it. I don't think we can officially support windows, but if you want to take a stab at changing our code to unofficially support it then feel free!

I had too many problems, so I ditched my Windows setup. Maybe we could add [Operating System classifiers ](https://pypi.org/pypi?%3Aaction=list_classifiers)so that people know that is isn't compatible ?
