### ISSUE TITLE
Installation failure on macOS High Sierra

### ISSUE THREAD

**Issue by shihabuddinbuet** [feast-dev/feast#1681]
```
Traceback (most recent call last):
  File "/usr/local/bin/feast", line 5, in <module>
    from feast.cli import cli
  File "/usr/local/lib/python3.9/site-packages/feast/__init__.py", line 5, in <module>
    from .client import Client
  File "/usr/local/lib/python3.9/site-packages/feast/client.py", line 26, in <module>
    from feast.data_source import BigQuerySource, FileSource
  File "/usr/local/lib/python3.9/site-packages/feast/data_source.py", line 19, in <module>
    from pyarrow.parquet import ParquetFile
  File "/usr/local/lib/python3.9/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/pyarrow/lib.cpython-39-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/lib/python3.9/site-packages/pyarrow/libarrow.400.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/python3.9/site-packages/pyarrow/libarrow.400.dylib
```

## Steps to reproduce
`pip install feast`
`feast --help`

### Specifications

- Version: 0.11.0
- Platform: Python: 3.9.5, Sierra

## Possible Solution
It might be the  issue in latest (4.0.1) version of `pyarrow` package. The older version `pyarrow==3.0.0` can be used until the issue is not solved in `pyarrow` newer versions.

**Comment by woop** [comment]
I'd like us to understand this problem a bit better. Pinning pyarrow to 3.0 is very restrictive. Which Python versions does this problem occur in, only 3.9?

**Comment by shihabuddinbuet** [comment]
I tested with both python 3.8 and 3.9. Unfortunately having same issue.
