### ISSUE TITLE
Feast apply fails

### ISSUE THREAD

**Issue by jainr** [feast-dev/feast#1774]
## Expected Behavior 
Following the quickstart, feast apply should work.

## Current Behavior
$ feast apply
Registered entity driver_id
Registered feature view driver_hourly_stats
Deploying infrastructure for driver_hourly_stats
Traceback (most recent call last):
  File "/Users/richinjain/opt/anaconda3/envs/r2p1d-deploy/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/Users/richinjain/opt/anaconda3/envs/r2p1d-deploy/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/richinjain/opt/anaconda3/envs/r2p1d-deploy/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/richinjain/opt/anaconda3/envs/r2p1d-deploy/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/richinjain/opt/anaconda3/envs/r2p1d-deploy/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/richinjain/opt/anaconda3/envs/r2p1d-deploy/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/richinjain/opt/anaconda3/envs/r2p1d-deploy/lib/python3.6/site-packages/feast/cli.py", line 160, in apply_total_command
    apply_total(repo_config, Path.cwd())
  File "/Users/richinjain/opt/anaconda3/envs/r2p1d-deploy/lib/python3.6/site-packages/feast/repo_operations.py", line 148, in apply_total
    partial=False,
  File "/Users/richinjain/opt/anaconda3/envs/r2p1d-deploy/lib/python3.6/site-packages/feast/infra/local.py", line 55, in update_infra
    conn = self._get_conn()
  File "/Users/richinjain/opt/anaconda3/envs/r2p1d-deploy/lib/python3.6/site-packages/feast/infra/local.py", line 45, in _get_conn
    self._db_path, detect_types=sqlite3.PARSE_DECLTYPES | sqlite3.PARSE_COLNAMES
TypeError: argument 1 must be str, not PosixPath

## Steps to reproduce
run - feast apply
### Specifications

- Version:  Feast SDK Version: "feast 0.10.2"

- Platform:MacOs
- Subsystem: Big Sur

**Comment by felixwang9817** [comment]
Hi @jainr, I suspect this is a Python version problem. Please upgrade to 3.7 and see if that fixes the problem. See [1502](https://github.com/feast-dev/feast/issues/1502).

**Comment by jainr** [comment]
You are right, I was actually able to resolve it by creating a fresh conda environment  with  python 3.7. Thanks for getting back to me.
