### ISSUE TITLE
[Alpha] AWS Lambda feature server - Error in deployment

### ISSUE THREAD

**Issue by sjagdeeshchandrap** [feast-dev/feast#1956]
## Expected Behavior 
The Lambda API should be deployed when feast apply command is run

## Current Behavior
We are getting file not found exception on running the command. See error below

Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/ec2-user/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/ec2-user/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/ec2-user/.local/lib/python3.7/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/home/ec2-user/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/feast/cli.py", line 339, in apply_total_command
    apply_total(repo_config, repo, skip_source_validation)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/feast/usage.py", line 210, in exception_logging_wrapper
    result = func(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/feast/repo_operations.py", line 203, in apply_total
    store.apply(all_to_apply, commit=False)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/feast/usage.py", line 210, in exception_logging_wrapper
    result = func(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/feast/feature_store.py", line 456, in apply
    partial=True,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/feast/infra/aws.py", line 86, in update_infra
    image_uri = self._upload_docker_image(project)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/feast/infra/aws.py", line 240, in _upload_docker_image
    docker_client = docker.from_env()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/docker/client.py", line 101, in from_env
    **kwargs_from_env(**kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/docker/api/client.py", line 222, in _retrieve_server_version
    f'Error while fetching server API version: {e}'
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

## Steps to reproduce
Please find below the yaml file

project: normal_lab
registry: s3://<bucket_name>/registries/normal_lab
provider: aws
online_store:
  type: dynamodb
  region: us-east-1
offline_store:
  type: redshift
  cluster_id: dim-featurestore
  region: us-east-1
  database: features
  user: <user>
  s3_staging_location: s3://<bucket_name>/features 
  iam_role: arn:aws:iam::<accno>:role/redshift-s3-admin-role
flags:
  alpha_features: true
  aws_lambda_feature_server: true
feature_server:
  enabled: true  
  execution_role_name: arn:aws:iam::<accno>:role/dim-featurestore-feast

### Specifications

- Version: 0.14
- Platform: Linux
- Subsystem:

**Comment by felixwang9817** [comment]
Hey @sjagdeeshchandrap, thanks for checking out the AWS Lambda feature server! It looks to me like your error is occurring since Docker isn't running:
```
File "/home/ec2-user/.local/lib/python3.7/site-packages/feast/infra/aws.py", line 240, in _upload_docker_image
docker_client = docker.from_env()
File "/home/ec2-user/.local/lib/python3.7/site-packages/docker/client.py", line 101, in from_env
**kwargs_from_env(**kwargs)
File "/home/ec2-user/.local/lib/python3.7/site-packages/docker/client.py", line 45, in init
self.api = APIClient(*args, **kwargs)
File "/home/ec2-user/.local/lib/python3.7/site-packages/docker/api/client.py", line 197, in init
self._version = self._retrieve_server_version()
File "/home/ec2-user/.local/lib/python3.7/site-packages/docker/api/client.py", line 222, in _retrieve_server_version
f'Error while fetching server API version: {e}'
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```
Can you make sure that you have the Docker desktop client installed and running, and then try again?
