### ISSUE TITLE
Feast CLI broken when updating version to 0.15.0 [Poetry installation]

### ISSUE THREAD

**Issue by gardneli** [feast-dev/feast#2026]
## Expected Behavior 
Running `poetry run feast version` should output:
> Feast SDK Version: "feast 0.15.0"

## Current Behavior
Running `poetry run feast version` outputs:

Traceback (most recent call last):
  File "/home/me/.cache/pypoetry/virtualenvs/test-feast-3ZjGyP2I-py3.8/bin/feast", line 5, in <module>
    from feast.cli import cli
  File "/home/me/.cache/pypoetry/virtualenvs/test-feast-3ZjGyP2I-py3.8/lib/python3.8/site-packages/feast/__init__.py", line 12, in <module>
    from .feature_service import FeatureService
  File "/home/me/.cache/pypoetry/virtualenvs/test-feast-3ZjGyP2I-py3.8/lib/python3.8/site-packages/feast/feature_service.py", line 6, in <module>
    from feast.base_feature_view import BaseFeatureView
  File "/home/me/.cache/pypoetry/virtualenvs/test-feast-3ZjGyP2I-py3.8/lib/python3.8/site-packages/feast/base_feature_view.py", line 19, in <module>
    from proto import Message
ModuleNotFoundError: No module named 'proto'

## Steps to reproduce
- [Install Poetry](https://python-poetry.org/docs/#installation)
- Create a new directory (e.g., test_feast)
- Run `poetry init` in the new directory and add feast as a dependency
- Run `poetry run feast version`

### Specifications

- Version: Feast 0.15.0
- Platform: Ubuntu 20.04.3 LTS
- Subsystem: CLI

## Possible Solution
At line 19 of feast/base_feature_view.py, change "from proto import Message" -> "from google.protobuf.message import Message"
At line 21 of feast/registry.py, change "from proto import Message" -> "from google.protobuf.message import Message"

**Comment by felixwang9817** [comment]
Hey @gardneli, thanks for reporting this issue. We're aware of it and have landed a [fix](https://github.com/feast-dev/feast/pull/2016) on master, which should make it out into the next patch release (0.15.1)!

**Comment by gardneli** [comment]
Fantastic - thanks for the update.  Also, just wanted to let you know that I really like your project and appreciate all the work you all have been doing on it.  Thank you!

**Comment by judahrand** [comment]
Can this be closed then?
