### ISSUE TITLE
[Windows] Feast does not support Windows

### ISSUE THREAD

**Issue by tmzn** [feast-dev/feast#2476]
Hi guys,

I'm not sure if I'm just doing something wrong or how I can fix it.

## Expected Behavior 

`feast apply` should scan (or ignore) all subdirectories for feature view/entity definitions.

## Current Behavior

If python files in subfolders are present, a `ModuleNotFoundError` is thrown:

```
$ feast apply
Traceback (most recent call last):
  File "C:\Users\username\Anaconda3\envs\py38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\username\Anaconda3\envs\py38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\Anaconda3\envs\py38\Scripts\feast.exe\__main__.py", line 7, in <module>
  File "C:\Users\username\Anaconda3\envs\py38\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\username\Anaconda3\envs\py38\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\username\Anaconda3\envs\py38\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\username\Anaconda3\envs\py38\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\username\Anaconda3\envs\py38\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\username\Anaconda3\envs\py38\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\username\Anaconda3\envs\py38\lib\site-packages\feast\cli.py", line 439, in apply_total_command
    apply_total(repo_config, repo, skip_source_validation)
  File "C:\Users\username\Anaconda3\envs\py38\lib\site-packages\feast\usage.py", line 280, in wrapper
    raise exc.with_traceback(traceback)
  File "C:\Users\username\Anaconda3\envs\py38\lib\site-packages\feast\usage.py", line 269, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\username\Anaconda3\envs\py38\lib\site-packages\feast\repo_operations.py", line 249, in apply_total
    project, registry, repo, store = _prepare_registry_and_repo(repo_config, repo_path)
  File "C:\Users\username\Anaconda3\envs\py38\lib\site-packages\feast\repo_operations.py", line 155, in _prepare_registry_and_repo
    repo = parse_repo(repo_path)
  File "C:\Users\username\Anaconda3\envs\py38\lib\site-packages\feast\repo_operations.py", line 108, in parse_repo
    module = importlib.import_module(module_path)
  File "C:\Users\username\Anaconda3\envs\py38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src\\foo'
```

## Steps to reproduce

```
$ feast init my_repo
$ cd my_repo
$ mkdir src
$ touch src/__init__.py
$ echo "print('hi')" > src/foo.py
$ feast apply
```

### Specifications

- Version: Feast SDK Version: "feast 0.19.3"
- Platform: Windows 10
- Python: Python 3.8.12
- Anaconda: conda 4.10.3

**Comment by achals** [comment]
Hi @tmzn , we unfortunately don't officially support windows right now - I believe users have had success using Feast on WSL, but that too isn't something that we officially support.
