### ISSUE TITLE
Unable to deploy feast 0.20.2 chart

### ISSUE THREAD

**Issue by psheorangithub** [feast-dev/feast#2657]
## Expected Behavior 
Chart should deploy successfully
## Current Behavior
Feature-server is crashing with following error, when deploying feast 0.20.2 chart.

bash-3.2$ k logs feast-feast-feature-server-64fd75c87-lrf7d -n feast
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 1]
  at ApplicationPropertiesModule.provideApplicationProperties(ApplicationPropertiesModule.java:40)
  at ServerModule.provideGrpcServer(ServerModule.java:43)
      \_ for 1st parameter
  at ServerModule.provideGrpcServer(ServerModule.java:43)
  while locating Server

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error

======================
Full classname legend:
======================
ApplicationPropertiesModule: "feast.serving.config.ApplicationPropertiesModule"
MismatchedInputException:    "com.fasterxml.jackson.databind.exc.MismatchedInputException"
Server:                      "io.grpc.Server"
ServerModule:                "feast.serving.config.ServerModule"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)
	at feast.serving.ServingGuiceApplication.main(ServingGuiceApplication.java:41)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:358)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2023)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1528)
	at feast.serving.config.ApplicationPropertiesModule.provideApplicationProperties(ApplicationPropertiesModule.java:49)
	at feast.serving.config.ApplicationPropertiesModule$$FastClassByGuice$$4840786.GUICE$TRAMPOLINE(<generated>)
	at feast.serving.config.ApplicationPropertiesModule$$FastClassByGuice$$4840786.apply(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100)
	... 2 more
bash-3.2$
## Steps to reproduce

Run the following commands to add the repository

helm repo add feast-charts https://feast-helm-charts.storage.googleapis.com
helm repo update

Install Feast

helm install feast-release feast-charts/feast
### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by adchia** [comment]
You aren't passing in the right yaml file to make it work. See https://github.com/feast-dev/feast/tree/master/examples/java-demo for a tutorial!
