### ISSUE TITLE
Error while use Postgres a offline store

### ISSUE THREAD

**Issue by II-VSB-II** [feast-dev/feast#2737]
## Steps to reproduce

**Redis Deployment:**
helm install --namespace kubeflow  my-redis bitnami/redis --set  master.persistence.enabled=false --set  replica.persistence.enabled=false --set global.redis.password=redis@123

**Postgres Deployment:**
helm install --namespace kubeflow my-postgres bitnami/postgresql --set primary.persistence.enabled=false --set readReplicas.persistence.enabled=false --set auth.postgresPassword=postgres@123 --set auth.username=feast --set auth.password=feast@123 --set auth.database=feast

**feature_store.yaml**
```
project: HousingPrediction
registry: /bd-fs-mnt/project_repo/feast/registry.db
provider: local
online_store:
  type: redis
  connection_string: "my-redis-master.kubelfow.svc.cluster.local:6379,password=redis@123"
offline_store:
  type: postgres
  host: "my-postgres-postgresql.kubeflow.svc.cluster.local"
  port: 5432
  db_schema: feast
  database: feast
  user: feast
  password: "feast@123"
```

**Error:**

Traceback (most recent call last):
  File "/home/dev1/.local/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/home/dev1/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/dev1/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/dev1/.local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dev1/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dev1/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/dev1/.local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dev1/.local/lib/python3.8/site-packages/feast/cli.py", line 541, in materialize_command
    store.materialize(
  File "/home/dev1/.local/lib/python3.8/site-packages/feast/usage.py", line 269, in wrapper
    return func(*args, **kwargs)
  File "/home/dev1/.local/lib/python3.8/site-packages/feast/feature_store.py", line 1194, in materialize
    provider.materialize_single_feature_view(
  File "/home/dev1/.local/lib/python3.8/site-packages/feast/infra/passthrough_provider.py", line 158, in materialize_single_feature_view
    offline_job = self.offline_store.pull_latest_from_table_or_query(
  File "/home/dev1/.local/lib/python3.8/site-packages/feast/usage.py", line 280, in wrapper
    raise exc.with_traceback(traceback)
  File "/home/dev1/.local/lib/python3.8/site-packages/feast/usage.py", line 269, in wrapper
    return func(*args, **kwargs)
  File "/home/dev1/.local/lib/python3.8/site-packages/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py", line 65, in pull_latest_from_table_or_query
    assert isinstance(data_source, PostgreSQLSource)

**definitions.py**

```
# This is an example feature definition file

from datetime import timedelta

from feast import Entity, FeatureService, FeatureView, Field, FileSource, ValueType
from feast.types import Float32, Int64, String


file1 = FileSource(
    path="/home/dev1/Feast-HP/HousingPrediction/data/train.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created",
)

file2 = FileSource(
    path="/home/dev1/Feast-HP/HousingPrediction/data/test.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created",
)

house = Entity(name="house_id", value_type=Int64, join_keys=["house_id"])

housing_price_train_view = FeatureView(
    name="housing_price_train",
    entities=["house_id"],
    schema=[
        Field(name="MSZoning", dtype=String),
        Field(name="Street", dtype=String),
        Field(name="Alley", dtype=String),
        Field(name="LotShape", dtype=String),
        Field(name="LandContour", dtype=String),
        Field(name="Utilities", dtype=String),
        Field(name="LotConfig", dtype=String),
        Field(name="LandSlope", dtype=String),
        Field(name="Neighborhood", dtype=String),
        Field(name="Condition1", dtype=String),
        Field(name="Condition2", dtype=String),
        Field(name="BldgType", dtype=String),
        Field(name="HouseStyle", dtype=String),
        Field(name="RoofStyle", dtype=String),
        Field(name="RoofMatl", dtype=String),
        Field(name="Exterior1st", dtype=String),
        Field(name="Exterior2nd", dtype=String),
        Field(name="MasVnrType", dtype=String),
        Field(name="ExterQual", dtype=String),
        Field(name="ExterCond", dtype=String),
        Field(name="Foundation", dtype=String),
        Field(name="BsmtQual", dtype=String),
        Field(name="BsmtCond", dtype=String),
        Field(name="BsmtExposure", dtype=String),
        Field(name="BsmtFinType1", dtype=String),
        Field(name="BsmtFinType2", dtype=String),
        Field(name="Heating", dtype=String),
        Field(name="HeatingQC", dtype=String),
        Field(name="CentralAir", dtype=String),
        Field(name="Electrical", dtype=String),
        Field(name="KitchenQual", dtype=String),
        Field(name="Functional", dtype=String),
        Field(name="FireplaceQu", dtype=String),
        Field(name="GarageType", dtype=String),
        Field(name="GarageFinish", dtype=String),
        Field(name="GarageQual", dtype=String),
        Field(name="GarageCond", dtype=String),
        Field(name="PavedDrive", dtype=String),
        Field(name="PoolQC", dtype=String),
        Field(name="Fence", dtype=String),
        Field(name="MiscFeature", dtype=String),
        Field(name="SaleType", dtype=String),
        Field(name="SaleCondition", dtype=String),
        Field(name="house_id", dtype=Int64),
        Field(name="MSSubClass", dtype=Int64),
        Field(name="LotArea", dtype=Int64),
        Field(name="OverallQual", dtype=Int64),
        Field(name="OverallCond", dtype=Int64),
        Field(name="YearBuilt", dtype=Int64),
        Field(name="YearRemodAdd", dtype=Int64),
        Field(name="BsmtFinSF1", dtype=Int64),
        Field(name="BsmtFinSF2", dtype=Int64),
        Field(name="BsmtUnfSF", dtype=Int64),
        Field(name="TotalBsmtSF", dtype=Int64),
        Field(name="1stFlrSF", dtype=Int64),
        Field(name="2ndFlrSF", dtype=Int64),
        Field(name="LowQualFinSF", dtype=Int64),
        Field(name="GrLivArea", dtype=Int64),
        Field(name="BsmtFullBath", dtype=Int64),
        Field(name="BsmtHalfBath", dtype=Int64),
        Field(name="FullBath", dtype=Int64),
        Field(name="HalfBath", dtype=Int64),
        Field(name="BedroomAbvGr", dtype=Int64),
        Field(name="KitchenAbvGr", dtype=Int64),
        Field(name="TotRmsAbvGrd", dtype=Int64),
        Field(name="Fireplaces", dtype=Int64),
        Field(name="GarageCars", dtype=Int64),
        Field(name="GarageArea", dtype=Int64),
        Field(name="WoodDeckSF", dtype=Int64),
        Field(name="OpenPorchSF", dtype=Int64),
        Field(name="EnclosedPorch", dtype=Int64),
        Field(name="3SsnPorch", dtype=Int64),
        Field(name="ScreenPorch", dtype=Int64),
        Field(name="PoolArea", dtype=Int64),
        Field(name="MiscVal", dtype=Int64),
        Field(name="MoSold", dtype=Int64),
        Field(name="YrSold", dtype=Int64),
        Field(name="SalePrice", dtype=Int64),
        Field(name="LotFrontage", dtype=Float32),
        Field(name="MasVnrArea", dtype=Float32),
        Field(name="GarageYrBlt", dtype=Float32)
    ],
    online=False,
    source=file1,
    tags={},
    ttl=timedelta(days=1),
)


housing_price_test_view = FeatureView(
    name="housing_price_test",
    entities=["house_id"],
    schema=[
        Field(name="MSZoning", dtype=String),
        Field(name="Street", dtype=String),
        Field(name="Alley", dtype=String),
        Field(name="LotShape", dtype=String),
        Field(name="LandContour", dtype=String),
        Field(name="Utilities", dtype=String),
        Field(name="LotConfig", dtype=String),
        Field(name="LandSlope", dtype=String),
        Field(name="Neighborhood", dtype=String),
        Field(name="Condition1", dtype=String),
        Field(name="Condition2", dtype=String),
        Field(name="BldgType", dtype=String),
        Field(name="HouseStyle", dtype=String),
        Field(name="RoofStyle", dtype=String),
        Field(name="RoofMatl", dtype=String),
        Field(name="Exterior1st", dtype=String),
        Field(name="Exterior2nd", dtype=String),
        Field(name="MasVnrType", dtype=String),
        Field(name="ExterQual", dtype=String),
        Field(name="ExterCond", dtype=String),
        Field(name="Foundation", dtype=String),
        Field(name="BsmtQual", dtype=String),
        Field(name="BsmtCond", dtype=String),
        Field(name="BsmtExposure", dtype=String),
        Field(name="BsmtFinType1", dtype=String),
        Field(name="BsmtFinType2", dtype=String),
        Field(name="Heating", dtype=String),
        Field(name="HeatingQC", dtype=String),
        Field(name="CentralAir", dtype=String),
        Field(name="Electrical", dtype=String),
        Field(name="KitchenQual", dtype=String),
        Field(name="Functional", dtype=String),
        Field(name="FireplaceQu", dtype=String),
        Field(name="GarageType", dtype=String),
        Field(name="GarageFinish", dtype=String),
        Field(name="GarageQual", dtype=String),
        Field(name="GarageCond", dtype=String),
        Field(name="PavedDrive", dtype=String),
        Field(name="PoolQC", dtype=String),
        Field(name="Fence", dtype=String),
        Field(name="MiscFeature", dtype=String),
        Field(name="SaleType", dtype=String),
        Field(name="SaleCondition", dtype=String),
        Field(name="house_id", dtype=Int64),
        Field(name="MSSubClass", dtype=Int64),
        Field(name="LotArea", dtype=Int64),
        Field(name="OverallQual", dtype=Int64),
        Field(name="OverallCond", dtype=Int64),
        Field(name="YearBuilt", dtype=Int64),
        Field(name="YearRemodAdd", dtype=Int64),
        Field(name="BsmtFinSF1", dtype=Int64),
        Field(name="BsmtFinSF2", dtype=Int64),
        Field(name="BsmtUnfSF", dtype=Int64),
        Field(name="TotalBsmtSF", dtype=Int64),
        Field(name="1stFlrSF", dtype=Int64),
        Field(name="2ndFlrSF", dtype=Int64),
        Field(name="LowQualFinSF", dtype=Int64),
        Field(name="GrLivArea", dtype=Int64),
        Field(name="BsmtFullBath", dtype=Int64),
        Field(name="BsmtHalfBath", dtype=Int64),
        Field(name="FullBath", dtype=Int64),
        Field(name="HalfBath", dtype=Int64),
        Field(name="BedroomAbvGr", dtype=Int64),
        Field(name="KitchenAbvGr", dtype=Int64),
        Field(name="TotRmsAbvGrd", dtype=Int64),
        Field(name="Fireplaces", dtype=Int64),
        Field(name="GarageCars", dtype=Int64),
        Field(name="GarageArea", dtype=Int64),
        Field(name="WoodDeckSF", dtype=Int64),
        Field(name="OpenPorchSF", dtype=Int64),
        Field(name="EnclosedPorch", dtype=Int64),
        Field(name="3SsnPorch", dtype=Int64),
        Field(name="ScreenPorch", dtype=Int64),
        Field(name="PoolArea", dtype=Int64),
        Field(name="MiscVal", dtype=Int64),
        Field(name="MoSold", dtype=Int64),
        Field(name="YrSold", dtype=Int64),
        Field(name="LotFrontage", dtype=Float32),
        Field(name="MasVnrArea", dtype=Float32),
        Field(name="GarageYrBlt", dtype=Float32)
    ],
    online=True,
    source=file2,
    tags={},
    ttl=timedelta(days=1),
)


housing_price_train_service = FeatureService(
    name="housing_price_train_service", features=[housing_price_train_view]
)

housing_price_test_service = FeatureService(
    name="housing_price_test_service", features=[housing_price_test_view]
)
```
### Specifications

- Version:  0.21.2

**Comment by pyalex** [comment]
Hi @II-VSB-II , currently you can use only one offline store per feature repo. So since you specified postgres as an offline store in your `feature_store.yaml`, all batch sources in your definitions should also be postgres sources. We know about this limitation and we have card in backlog to support multiple offline stores.

Closing as duplicate.

**Comment by II-VSB-II** [comment]
I have 1 offline_store (postgres) and 1 online_store (redis) in my feature_store.yaml.

**Comment by II-VSB-II** [comment]
**feature_store.yaml**
```
project: HousingPredictionOffline
registry: /bd-fs-mnt/project_repo/feast/online_registry.db
provider: local
offline_store:
  type: postgres
  host: "my-postgres-postgresql.kubeflow.svc.cluster.local"
  port: 5432
  db_schema: feast
  database: feast
  user: feast
  password: "feast@123"
```

**definitions_offline.py**
```
from datetime import timedelta

from feast import Entity, FeatureService, FeatureView, Field, FileSource, ValueType
from feast.types import Float32, Int64, String

file2 = FileSource(
    path="/home/dev1/Feast-HP/HousingPrediction/data/test.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created",
)

house = Entity(name="house_id", value_type=Int64, join_keys=["house_id"])

housing_price_test_view = FeatureView(
    name="housing_price_test",
    entities=["house_id"],
    schema=[
        Field(name="MSZoning", dtype=String),
        Field(name="Street", dtype=String),
        Field(name="Alley", dtype=String),
        Field(name="LotShape", dtype=String),
        Field(name="LandContour", dtype=String),
        Field(name="Utilities", dtype=String),
        Field(name="LotConfig", dtype=String),
        Field(name="LandSlope", dtype=String),
        Field(name="Neighborhood", dtype=String),
        Field(name="Condition1", dtype=String),
        Field(name="Condition2", dtype=String),
        Field(name="BldgType", dtype=String),
        Field(name="HouseStyle", dtype=String),
        Field(name="RoofStyle", dtype=String),
        Field(name="RoofMatl", dtype=String),
        Field(name="Exterior1st", dtype=String),
        Field(name="Exterior2nd", dtype=String),
        Field(name="MasVnrType", dtype=String),
        Field(name="ExterQual", dtype=String),
        Field(name="ExterCond", dtype=String),
        Field(name="Foundation", dtype=String),
        Field(name="BsmtQual", dtype=String),
        Field(name="BsmtCond", dtype=String),
        Field(name="BsmtExposure", dtype=String),
        Field(name="BsmtFinType1", dtype=String),
        Field(name="BsmtFinType2", dtype=String),
        Field(name="Heating", dtype=String),
        Field(name="HeatingQC", dtype=String),
        Field(name="CentralAir", dtype=String),
        Field(name="Electrical", dtype=String),
        Field(name="KitchenQual", dtype=String),
        Field(name="Functional", dtype=String),
        Field(name="FireplaceQu", dtype=String),
        Field(name="GarageType", dtype=String),
        Field(name="GarageFinish", dtype=String),
        Field(name="GarageQual", dtype=String),
        Field(name="GarageCond", dtype=String),
        Field(name="PavedDrive", dtype=String),
        Field(name="PoolQC", dtype=String),
        Field(name="Fence", dtype=String),
        Field(name="MiscFeature", dtype=String),
        Field(name="SaleType", dtype=String),
        Field(name="SaleCondition", dtype=String),
        Field(name="house_id", dtype=Int64),
        Field(name="MSSubClass", dtype=Int64),
        Field(name="LotArea", dtype=Int64),
        Field(name="OverallQual", dtype=Int64),
        Field(name="OverallCond", dtype=Int64),
        Field(name="YearBuilt", dtype=Int64),
        Field(name="YearRemodAdd", dtype=Int64),
        Field(name="BsmtFinSF1", dtype=Int64),
        Field(name="BsmtFinSF2", dtype=Int64),
        Field(name="BsmtUnfSF", dtype=Int64),
        Field(name="TotalBsmtSF", dtype=Int64),
        Field(name="1stFlrSF", dtype=Int64),
        Field(name="2ndFlrSF", dtype=Int64),
        Field(name="LowQualFinSF", dtype=Int64),
        Field(name="GrLivArea", dtype=Int64),
        Field(name="BsmtFullBath", dtype=Int64),
        Field(name="BsmtHalfBath", dtype=Int64),
        Field(name="FullBath", dtype=Int64),
        Field(name="HalfBath", dtype=Int64),
        Field(name="BedroomAbvGr", dtype=Int64),
        Field(name="KitchenAbvGr", dtype=Int64),
        Field(name="TotRmsAbvGrd", dtype=Int64),
        Field(name="Fireplaces", dtype=Int64),
        Field(name="GarageCars", dtype=Int64),
        Field(name="GarageArea", dtype=Int64),
        Field(name="WoodDeckSF", dtype=Int64),
        Field(name="OpenPorchSF", dtype=Int64),
        Field(name="EnclosedPorch", dtype=Int64),
        Field(name="3SsnPorch", dtype=Int64),
        Field(name="ScreenPorch", dtype=Int64),
        Field(name="PoolArea", dtype=Int64),
        Field(name="MiscVal", dtype=Int64),
        Field(name="MoSold", dtype=Int64),
        Field(name="YrSold", dtype=Int64),
        Field(name="LotFrontage", dtype=Float32),
        Field(name="MasVnrArea", dtype=Float32),
        Field(name="GarageYrBlt", dtype=Float32)
    ],
    online=True,
    source=file2,
    tags={},
    ttl=timedelta(days=1),
)



housing_price_test_service = FeatureService(
    name="housing_price_test_service", features=[housing_price_test_view]
)
```


**Error:**
bash-4.2$ feast apply
Created entity house_id
Created feature view housing_price_test
Created feature service housing_price_test_service

Created sqlite table HousingPredictionOffline_housing_price_test

bash-4.2$ ls
data  definitions_offline.py  feature_store.yaml
bash-4.2$ CURRENT_TIME=$(date -u +"%Y-%m-%dT%H:%M:%S")
bash-4.2$ feast materialize 2021-12-27 $CURRENT_TIME
Materializing 1 feature views from 2021-12-27 00:00:00+00:00 to 2022-05-30 04:50:57+00:00 into the sqlite online store.

housing_price_test:
Traceback (most recent call last):
  File "/home/dev1/.local/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/home/dev1/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/dev1/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/dev1/.local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dev1/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dev1/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/dev1/.local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dev1/.local/lib/python3.8/site-packages/feast/cli.py", line 541, in materialize_command
    store.materialize(
  File "/home/dev1/.local/lib/python3.8/site-packages/feast/usage.py", line 269, in wrapper
    return func(*args, **kwargs)
  File "/home/dev1/.local/lib/python3.8/site-packages/feast/feature_store.py", line 1194, in materialize
    provider.materialize_single_feature_view(
  File "/home/dev1/.local/lib/python3.8/site-packages/feast/infra/passthrough_provider.py", line 158, in materialize_single_feature_view
    offline_job = self.offline_store.pull_latest_from_table_or_query(
  File "/home/dev1/.local/lib/python3.8/site-packages/feast/usage.py", line 280, in wrapper
    raise exc.with_traceback(traceback)
  File "/home/dev1/.local/lib/python3.8/site-packages/feast/usage.py", line 269, in wrapper
    return func(*args, **kwargs)
  File "/home/dev1/.local/lib/python3.8/site-packages/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py", line 65, in pull_latest_from_table_or_query
    assert isinstance(data_source, PostgreSQLSource)
AssertionError
bash-4.2$

**Comment by achals** [comment]
@II-VSB-II The problem is that if you're using `Postgres` as the offline store, you can't use a `FileSource`, or any other source other than `PostgreSQLSource`.
