### ISSUE TITLE
Spark source unable to accept parquet file folder path

### ISSUE THREAD

**Issue by yash-ghelani-dsw** [feast-dev/feast#2921]
Spark source has been working well with providing a single parquet file path. But when a folder path is provided it shows following error:

```
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
07/07/2022 02:43:18 PM ERROR:Spark read of file source failed.
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\feast\infra\offline_stores\contrib\spark_offline_store\spark_source.py", line 184, in get_table_query_string
    df = spark_session.read.format(self.file_format).load(self.path)
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\pyspark\sql\readwriter.py", line 204, in load
    return self._df(self._jreader.load(path))
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\py4j\java_gateway.py", line 1304, in __call__
    return_value = get_return_value(
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\pyspark\sql\utils.py", line 117, in deco
    raise converted from None
pyspark.sql.utils.AnalysisException: Path does not exist: file:/data
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\feast\infra\offline_stores\contrib\spark_offline_store\spark_source.py", line 184, in get_table_query_string
    df = spark_session.read.format(self.file_format).load(self.path)
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\pyspark\sql\readwriter.py", line 204, in load
    return self._df(self._jreader.load(path))
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\py4j\java_gateway.py", line 1304, in __call__
    return_value = get_return_value(
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\pyspark\sql\utils.py", line 117, in deco
    raise converted from None
pyspark.sql.utils.AnalysisException: Path does not exist: file:/data
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\anaconda3\envs\feast_21\Scripts\feast.exe\__main__.py", line 7, in <module>
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\feast\cli.py", line 489, in apply_total_command
    apply_total(repo_config, repo, skip_source_validation)
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\feast\usage.py", line 280, in wrapper
    raise exc.with_traceback(traceback)
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\feast\usage.py", line 269, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\feast\repo_operations.py", line 276, in apply_total
    apply_total_with_repo_instance(
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\feast\repo_operations.py", line 234, in apply_total_with_repo_instance
    data_source.validate(store.config)
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\feast\infra\offline_stores\contrib\spark_offline_store\spark_source.py", line 149, in validate
    self.get_table_column_names_and_types(config)
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\feast\infra\offline_stores\contrib\spark_offline_store\spark_source.py", line 165, in get_table_column_names_and_types
    df = spark_session.sql(f"SELECT * FROM {self.get_table_query_string()}")
  File "C:\Users\Admin\anaconda3\envs\feast_21\lib\site-packages\feast\infra\offline_stores\contrib\spark_offline_store\spark_source.py", line 190, in get_table_query_string
    df.createOrReplaceTempView(tmp_table_name)
UnboundLocalError: local variable 'df' referenced before assignment
```

**Comment by achals** [comment]
Seems like the error is different in your stack trace:

> pyspark.sql.utils.AnalysisException: Path does not exist: file:/data

I think this may have to do with your setup or data location, and not feast? Feel free to reopen if that's not the case.

**Comment by yash-ghelani-dsw** [comment]
> Seems like the error is different in your stack trace:
> 
> > pyspark.sql.utils.AnalysisException: Path does not exist: file:/data
> 
> I think this may have to do with your setup or data location, and not feast? Feel free to reopen if that's not the case.

07/08/2022 10:59:59 AM feast.infra.offline_stores.contrib.spark_offline_store.spark_source ERROR: Spark read of file source failed.
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\feast\infra\offline_stores\contrib\spark_offline_store\spark_source.py", line 186, in get_table_query_string
    df = spark_session.read.format(self.file_format).load(self.path)
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\pyspark\sql\readwriter.py", line 204, in load
    return self._df(self._jreader.load(path))
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\py4j\java_gateway.py", line 1304, in __call__
    return_value = get_return_value(
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\pyspark\sql\utils.py", line 111, in deco
    return f(*a, **kw)
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\py4j\protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o48.load.
: java.lang.UnsatisfiedLinkError: org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Ljava/lang/String;I)Z
        at org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Native Method)
        at org.apache.hadoop.io.nativeio.NativeIO$Windows.access(NativeIO.java:645)
        at org.apache.hadoop.fs.FileUtil.canRead(FileUtil.java:1230)
        at org.apache.hadoop.fs.FileUtil.list(FileUtil.java:1435)
        at org.apache.hadoop.fs.RawLocalFileSystem.listStatus(RawLocalFileSystem.java:493)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1868)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1910)
        at org.apache.hadoop.fs.ChecksumFileSystem.listStatus(ChecksumFileSystem.java:678)
        at org.apache.spark.util.HadoopFSUtils$.listLeafFiles(HadoopFSUtils.scala:225)
        at org.apache.spark.util.HadoopFSUtils$.$anonfun$parallelListLeafFilesInternal$1(HadoopFSUtils.scala:95)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at org.apache.spark.util.HadoopFSUtils$.parallelListLeafFilesInternal(HadoopFSUtils.scala:85)
        at org.apache.spark.util.HadoopFSUtils$.parallelListLeafFiles(HadoopFSUtils.scala:69)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex$.bulkListLeafFiles(InMemoryFileIndex.scala:158)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.listLeafFiles(InMemoryFileIndex.scala:131)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.refresh0(InMemoryFileIndex.scala:94)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.<init>(InMemoryFileIndex.scala:66)
        at org.apache.spark.sql.execution.datasources.DataSource.createInMemoryFileIndex(DataSource.scala:581)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:417)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:325)
        at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:307)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:307)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:239)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Unknown Source)

Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\feast\infra\offline_stores\contrib\spark_offline_store\spark_source.py", line 186, in get_table_query_string
    df = spark_session.read.format(self.file_format).load(self.path)
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\pyspark\sql\readwriter.py", line 204, in load
    return self._df(self._jreader.load(path))
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\py4j\java_gateway.py", line 1304, in __call__
    return_value = get_return_value(
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\pyspark\sql\utils.py", line 111, in deco
    return f(*a, **kw)
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\py4j\protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o48.load.
: java.lang.UnsatisfiedLinkError: org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Ljava/lang/String;I)Z
        at org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Native Method)
        at org.apache.hadoop.io.nativeio.NativeIO$Windows.access(NativeIO.java:645)
        at org.apache.hadoop.fs.FileUtil.canRead(FileUtil.java:1230)
        at org.apache.hadoop.fs.FileUtil.list(FileUtil.java:1435)
        at org.apache.hadoop.fs.RawLocalFileSystem.listStatus(RawLocalFileSystem.java:493)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1868)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1910)
        at org.apache.hadoop.fs.ChecksumFileSystem.listStatus(ChecksumFileSystem.java:678)
        at org.apache.spark.util.HadoopFSUtils$.listLeafFiles(HadoopFSUtils.scala:225)
        at org.apache.spark.util.HadoopFSUtils$.$anonfun$parallelListLeafFilesInternal$1(HadoopFSUtils.scala:95)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at org.apache.spark.util.HadoopFSUtils$.parallelListLeafFilesInternal(HadoopFSUtils.scala:85)
        at org.apache.spark.util.HadoopFSUtils$.parallelListLeafFiles(HadoopFSUtils.scala:69)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex$.bulkListLeafFiles(InMemoryFileIndex.scala:158)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.listLeafFiles(InMemoryFileIndex.scala:131)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.refresh0(InMemoryFileIndex.scala:94)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.<init>(InMemoryFileIndex.scala:66)
        at org.apache.spark.sql.execution.datasources.DataSource.createInMemoryFileIndex(DataSource.scala:581)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:417)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:325)
        at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:307)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:307)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:239)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Unknown Source)

Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\anaconda3\envs\feast_22\Scripts\feast.exe\__main__.py", line 7, in <module>
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\feast\cli.py", line 492, in apply_total_command
    apply_total(repo_config, repo, skip_source_validation)
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\feast\usage.py", line 280, in wrapper
    raise exc.with_traceback(traceback)
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\feast\usage.py", line 269, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\feast\repo_operations.py", line 305, in apply_total
    apply_total_with_repo_instance(
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\feast\repo_operations.py", line 263, in apply_total_with_repo_instance
    data_source.validate(store.config)
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\feast\infra\offline_stores\contrib\spark_offline_store\spark_source.py", line 151, in validate
    self.get_table_column_names_and_types(config)
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\feast\infra\offline_stores\contrib\spark_offline_store\spark_source.py", line 167, in get_table_column_names_and_types
    df = spark_session.sql(f"SELECT * FROM {self.get_table_query_string()}")
  File "C:\Users\Admin\anaconda3\envs\feast_22\lib\site-packages\feast\infra\offline_stores\contrib\spark_offline_store\spark_source.py", line 192, in get_table_query_string
    df.createOrReplaceTempView(tmp_table_name)
UnboundLocalError: local variable 'df' referenced before assignment

Still it gives error when providing folder path to spark source... and work perfectly when provided path to a single parquet file
