### ISSUE TITLE
Redis Materialization fails: wrong number of arguments for 'hset' command

### ISSUE THREAD

**Issue by adamschmidt** [feast-dev/feast#2953]
## Expected Behavior 

Materialization from a Snowflake offline store to a Redis online store completes successfully

## Current Behavior

Running the materialize-incremental CLI command (Snowflake -> Redis) fails with the following message:

```
redis.exceptions.ResponseError: Command # 1 (HSET ACCOUNT_ID�<project name> _ts:<feature view name>��ז ��Cp 5 ��y� 5 4�> ) of pipeline caused error: wrong number of arguments for 'hset' command
```

## Steps to reproduce

* Set up feature services and feature views
* Provision redis store
* Create offline dataset in Snowflake
* Configure `feature_store.yaml` with Snowflake offline/Redis online stores
* Run `feast materialize-incremental <timestamp>`
* Wait for crash

### Specifications

- Version: 0.22.1
- Platform: Python 3.10, Linux, Docker
- Subsystem: AWS EKS

## Possible Solution

Unsure. Possibly issues with the bytes being written as either the key or value?

**Comment by m0hitbansal** [comment]
I am getting same issue 
`b'\x02\x00\x00\x00merchant_id\x02\x00\x00\x00source\x04\x00\x00\x00\x08\x00\x00\x00\x98\xf7\x81\x00\x00\x00\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00PAYUfraud_demo' {'_ts:merchant_featureview': b'\x08\xc6\xa5\x8a\x98\x06', b'!2\x1e\xe2': b')\x00\x00\x00\x00\x00\x00\x00\x00', b'\xfag\x86\x90': b')\x00\x00\x00\x00\x00\x00\x00\x00', b'\xa0(2\xde': b')\x00\x00\x00\x00\x00\x00\x00\x00', b'@q?\xae': b')\x00\x00\x00\x00\x00\x00\x00\x00', b'$\xe0)W': b')\x00\x00\x00\x00\x00\x00\x00\x00', b'5\xe6\x87\xae': b')\x00\x00\x00\x00\x00\x00\x00\x00', b'\xbeD:-': b')\x00\x00\x00\x00\x00\x00\x00\x00', b'\xf3E\x9dX': b')\x00\x00\x00\x00\x00\x00\x00\x00', b'\xf2\xef&\xe5': b')\x00\x00\x00\x00\x00\x00\x00\x00', b')@\x957': b' \x00', b'\x9d\xca\xcfD': b')\x00\x00\x00\x00\x00\x00\x00\x00'}
  0%|                                                                       | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "module_change.py", line 91, in <module>
    feast_materialize(start_time,end_time)
  File "module_change.py", line 51, in feast_materialize
    store.materialize(
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/feast/usage.py", line 276, in wrapper
    return func(*args, **kwargs)
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/feast/feature_store.py", line 1342, in materialize
    provider.materialize_single_feature_view(
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/feast/infra/passthrough_provider.py", line 251, in materialize_single_feature_view
    raise e
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/feast/infra/materialization/local_engine.py", line 173, in _materialize_one
    self.online_store.online_write_batch(
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/feast/usage.py", line 287, in wrapper
    raise exc.with_traceback(traceback)
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/feast/usage.py", line 276, in wrapper
    return func(*args, **kwargs)
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/feast/infra/online_stores/redis.py", line 243, in online_write_batch
    results = pipe.execute()
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/redis/client.py", line 2058, in execute
    return conn.retry.call_with_retry(
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/redis/retry.py", line 45, in call_with_retry
    return do()
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/redis/client.py", line 2059, in <lambda>
    lambda: execute(conn, stack, raise_on_error),
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/redis/client.py", line 1980, in _execute_pipeline
    self.raise_first_error(commands, response)
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/redis/client.py", line 1987, in raise_first_error
    raise r
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/redis/client.py", line 1975, in _execute_pipeline
    response.append(self.parse_response(connection, args[0], **options))
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/redis/client.py", line 1998, in parse_response
    result = Redis.parse_response(self, connection, command_name, **options)
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/redis/client.py", line 1234, in parse_response
    response = connection.read_response()
  File "/home/mohit-bansal/international-fraud-model/env/lib/python3.8/site-packages/redis/connection.py", line 836, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (HSET merchant_idsourc��BCfraud_demo _ts:merchant_featureviewƥ�� !2� )
�����? �g�� )�Z����? �(2� )�wI�
(s? @q?� )�wI�
(s? $�)W ) 5懮 ) �D:- ) �E�X ) ��&� ) )@�7   ���D )) of pipeline caused error: wrong number of arguments for 'hset' command`

**Comment by sfc-gh-madkins** [comment]
@m0hitbansal @adamschmidt were you ever able to resolve this issue? Can you add more details about your project?

**Comment by sfc-gh-madkins** [comment]
bump
