### ISSUE TITLE
feast ui won't launch (following feast-workshop/module_2)

### ISSUE THREAD

**Issue by m10an** [feast-dev/feast#3081]
## Current Behavior
```shell
$ feast ui

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/feast/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/feast/cli.py", line 150, in ui
    registry_ttl_sec=registry_ttl_sec,
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/feast/usage.py", line 276, in wrapper
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/feast/feature_store.py", line 2240, in serve_ui
    registry_ttl_sec=registry_ttl_sec,
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/feast/ui_server.py", line 100, in start_server
    app = get_app(store, get_registry_dump, project_id, registry_ttl_sec, host, port)
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/feast/ui_server.py", line 54, in get_app
    async_refresh()
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/feast/ui_server.py", line 40, in async_refresh
    registry_json = get_registry_dump(store.config, store.repo_path)
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/feast/usage.py", line 287, in wrapper
    raise exc.with_traceback(traceback)
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/feast/usage.py", line 276, in wrapper
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/feast/repo_operations.py", line 323, in registry_dump
    registry_dict = registry.to_dict(project=project)
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/feast/registry.py", line 733, in to_dict
    on_demand_feature_view.udf
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/dill/source.py", line 354, in getsource
    lines, lnum = getsourcelines(object, enclosing=enclosing)
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/dill/source.py", line 325, in getsourcelines
    code, n = getblocks(object, lstrip=lstrip, enclosing=enclosing, locate=True)
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/dill/source.py", line 251, in getblocks
    lines, lnum = findsource(object)
  File "/home/user/anaconda3/envs/feast/lib/python3.7/site-packages/dill/source.py", line 195, in findsource
    line = lines[lnum]
IndexError: list index out of range
```

## Steps to reproduce
```shell
conda create -n feast python=3.7
conda activate feast
```
then steps 1, 4, 5, 6 from [feast-workshop/module_2](https://github.com/feast-dev/feast-workshop/tree/main/module_2#step-6-optional-explore-the-repository-in-the-web-ui)

### Specifications

- Version: 0.22.3
- Platform: Ubuntu 20.04.4

## Possible Solution
No idea, only trying to get started

**Comment by adchia** [comment]
This was fixed already. Cutting a patch release now!
