### ISSUE TITLE
sql registry bug 

### ISSUE THREAD

**Issue by hao-affirm** [feast-dev/feast#3097]
## Expected Behavior 
`feast apply` success

## Current Behavior
```
➜  feast git:(master) feast apply
{'project': 'prod', 'registry': {'registry_type': 'sql', 'path': 'mysql://root@localhost/feast'}, 'provider': 'local', 'online_store': {'path': 'data/online_store.db'}, 'entity_key_serialization_version': 2}
registry=RegistryConfig(registry_type='sql', registry_store_type=None, path='mysql://root@localhost/feast', cache_ttl_seconds=600) project='prod' provider='local' feature_server=None flags=None repo_path=PosixPath('/Users/hao.xu/dev/all-the-things/ml2/feast/affirm/ml2/feast') go_feature_serving=False go_feature_retrieval=False entity_key_serialization_version=2 offline_store={'type': 'file'} online_store={'path': 'data/online_store.db', 'type': 'sqlite'} _offline_store=None _offline_config='file' _online_store=None _online_config={'path': 'data/online_store.db', 'type': 'sqlite'} _batch_engine=None _batch_engine_config='local'
Created entity dummy_entity
Created feature view dummy
Created feature service dummy_service

Traceback (most recent call last):
  File "/Users/hao.xu/.pyenv/versions/3.7.13/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/Users/hao.xu/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hao.xu/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/hao.xu/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hao.xu/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hao.xu/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/hao.xu/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/hao.xu/dev/feast/sdk/python/feast/cli.py", line 496, in apply_total_command
    apply_total(repo_config, repo, skip_source_validation)
  File "/Users/hao.xu/dev/feast/sdk/python/feast/usage.py", line 276, in wrapper
    return func(*args, **kwargs)
  File "/Users/hao.xu/dev/feast/sdk/python/feast/repo_operations.py", line 307, in apply_total
    store, project, registry, repo, skip_source_validation
  File "/Users/hao.xu/dev/feast/sdk/python/feast/repo_operations.py", line 279, in apply_total_with_repo_instance
    store._apply_diffs(registry_diff, infra_diff, new_infra)
  File "/Users/hao.xu/dev/feast/sdk/python/feast/usage.py", line 287, in wrapper
    raise exc.with_traceback(traceback)
  File "/Users/hao.xu/dev/feast/sdk/python/feast/usage.py", line 276, in wrapper
    return func(*args, **kwargs)
  File "/Users/hao.xu/dev/feast/sdk/python/feast/feature_store.py", line 742, in _apply_diffs
    self._registry.update_infra(new_infra, self.project, commit=True)
  File "/Users/hao.xu/dev/feast/sdk/python/feast/infra/registry_stores/sql.py", line 559, in update_infra
    managed_infra, project, "infra_name", infra, "infra_proto", name="infra_obj"
  File "/Users/hao.xu/dev/feast/sdk/python/feast/infra/registry_stores/sql.py", line 699, in _apply_object
    assert name, f"name needs to be provided for {obj}"
AssertionError: name needs to be provided for Infra(infra_objects=[<feast.infra.online_stores.sqlite.SqliteTable object at 0x151f983d0>])
```
### Specifications

- Version: 0.23.2
- Platform: macOS
- Subsystem:

## Possible Solution
in pr: https://github.com/feast-dev/feast/pull/3096

**Comment by felixwang9817** [comment]
resolved by #3096
