### ISSUE TITLE
Unable to run feast with local postgres backend

### ISSUE THREAD

**Issue by asafalina** [feast-dev/feast#3116]
I'm trying to run Feast on local machine with postgres serving as the storage (running as a docker container).  
I'm following the [official guide](https://docs.feast.dev/getting-started/quickstart), with the only difference being the postgres as the storage (instead of file-based).

## Steps to reproduce

Run:
`feast init -t postgres feature_repo`

The generated `feature_repo` folder contain the below contents:
```
.
|-- __init__.py
|-- driver_repo.py
|-- feature_store.yaml
`-- test.py
```

The generated `feature_store.yaml` file looks as follows:
```
project: feature_repo
provider: local
registry:
    registry_store_type: PostgreSQLRegistryStore
    path: feast_registry
    host: localhost
    port: 5432
    database: tmp
    db_schema: public
    user: root
    password: root
online_store:
    type: postgres
    host: localhost
    port: 5432
    database: tmp
    db_schema: public
    user: root
    password: root
offline_store:
    type: postgres
    host: localhost
    port: 5432
    database: tmp
    db_schema: public
    user: root
    password: root
entity_key_serialization_version: 2
```

(I made sure that the provided postgres credentials are correct)

Inside the `feature_repo` folder I run `feast apply`, and I'm getting the below error:

```
Traceback (most recent call last):
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 1128, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 1164, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/google/protobuf/internal/decoder.py", line 174, in ReadTag
    while buffer[pos] & 0x80:
TypeError: unsupported operand type(s) for &: 'bytes' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/feast/cli.py", line 495, in apply_total_command
    apply_total(repo_config, repo, skip_source_validation)
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/feast/usage.py", line 287, in wrapper
    raise exc.with_traceback(traceback)
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/feast/usage.py", line 276, in wrapper
    return func(*args, **kwargs)
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/feast/repo_operations.py", line 304, in apply_total
    project, registry, repo, store = _prepare_registry_and_repo(repo_config, repo_path)
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/feast/repo_operations.py", line 192, in _prepare_registry_and_repo
    store = FeatureStore(config=repo_config)
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/feast/usage.py", line 325, in wrapper
    return func(*args, **kwargs)
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/feast/feature_store.py", line 146, in __init__
    r._initialize_registry(self.config.project)
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/feast/registry.py", line 859, in _initialize_registry
    self._get_registry_proto(project=project)
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/feast/registry.py", line 1835, in _get_registry_proto
    registry_proto = self._registry_store.get_registry_proto()
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/feast/infra/registry_stores/contrib/postgres/registry_store.py", line 61, in get_registry_proto
    registry_proto = registry_proto.FromString(row[0])
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 801, in FromString
    message.MergeFromString(s)
  File "/Users/my-user/Desktop/my-user/repos/feast_playground/.venv/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 1134, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
```

### Specifications

- Version: 0.23.1
- Platform: MacOS M1

**Comment by asafalina** [comment]
doing this fix the issue:

```
brew install protobuf
export CFLAGS="-I$(brew --prefix protobuf)/include"
export LDFLAGS="-L$(brew --prefix protobuf)/lib"

# You need
pip install protobuf==3.17 --force-reinstall --no-deps --install-option="--cpp_implementation"
```

(credits to this: https://github.com/feast-dev/feast/issues/2105)
