### ISSUE TITLE
feast.errors.FeastClassImportError: Could not import class 'MyCustomEngine' from module 'feast_custom_engine'

### ISSUE THREAD

**Issue by newsbreak-tonglin** [feast-dev/feast#3197]
try to add a custom engine(https://docs.feast.dev/how-to-guides/customizing-feast/creating-a-custom-materialization-engine), but got some errors below:
feast.errors.FeastClassImportError: Could not import class 'MyCustomEngine' from module 'feast_custom_engine'

my project structure:
.
├── __init__.py
├── data
│   ├── driver_stats.parquet
│   ├── online_store.db
│   └── registry.db
├── entity_example.py
├── example.py
├── feast_custom_engine
│   ├── __init__.py
│   ├── __pycache__
│   │   └── __init__.cpython-38.pyc
│   └── my_custom_engine.py
└── feature_store.yaml

command:  PYTHONPATH=$PYTHONPATH:/Users/xx/feast_test/my_project/feast_custom_engine feast --log-level DEBUG materialize 2022-01-01 2022-12-12

error details: Traceback (most recent call last):
  File "/Users/xx/.pyenv/versions/3.8.10/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/Users/xx/.pyenv/versions/3.8.10/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xx/.pyenv/versions/3.8.10/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/xx/.pyenv/versions/3.8.10/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xx/.pyenv/versions/3.8.10/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xx/.pyenv/versions/3.8.10/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/xx/.pyenv/versions/3.8.10/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/xx/.pyenv/versions/3.8.10/lib/python3.8/site-packages/feast/cli.py", line 550, in materialize_command
    store.materialize(
  File "/Users/xx/.pyenv/versions/3.8.10/lib/python3.8/site-packages/feast/usage.py", line 285, in wrapper
    raise exc.with_traceback(traceback)
  File "/Users/xx/.pyenv/versions/3.8.10/lib/python3.8/site-packages/feast/usage.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/Users/xx/.pyenv/versions/3.8.10/lib/python3.8/site-packages/feast/feature_store.py", line 1342, in materialize
    provider.materialize_single_feature_view(
  File "/Users/xx/.pyenv/versions/3.8.10/lib/python3.8/site-packages/feast/infra/passthrough_provider.py", line 246, in materialize_single_feature_view
    jobs = self.batch_engine.materialize(registry, [task])
  File "/Users/xx/.pyenv/versions/3.8.10/lib/python3.8/site-packages/feast/infra/passthrough_provider.py", line 89, in batch_engine
    engine_class = importer.import_class(engine_module, engine_class_name)
  File "/Users/xx/.pyenv/versions/3.8.10/lib/python3.8/site-packages/feast/importer.py", line 41, in import_class
    raise FeastClassImportError(module_name, class_name) from None
feast.errors.FeastClassImportError: Could not import class 'MyCustomEngine' from module 'feast_custom_engine'

**Comment by niklasvm** [comment]
What does your `feature_store.yaml` look like? Based on your screenshot I would expect this to work:
```
batch_engine: feature_custom_engine.feast_custom_engine.MyCustomEngine
```

**Comment by newsbreak-tonglin** [comment]
@niklasvm feature_custom_engine.feast_custom_engine.MyCustomEngine doesn't work, below is my  feature_store.yaml

project: my_project
registry: data/registry.db
batch_engine: feature_custom_engine.feast_custom_engine.MyCustomEngine
provider: local
online_store:
    path: data/online_store.db
offline_store:
  type: file

**Comment by mehmettokgoz** [comment]
Hi @newsbreak-tonglin, did you solve this issue? I'm getting a similar error while trying to implement a custom store.
