### ISSUE TITLE
AttributeError: module 'google.cloud.bigquery.job' has no attribute 'query' using google-cloud-bigquery 2.1.0

### ISSUE THREAD

**Issue by breno-costa** [feast-dev/feast#3205]
## Expected Behavior 

I have found a corner case trying to install feast as dependency in a project. Poetry solved `google-cloud-bigquery` to `2.1.0` when installing `feast[gcp,redis]==0.24.1` along with other dependencies. But I was not able to use feast after installing it. 

## Current Behavior

I got the following exception when running the command `feast apply`:

```python
Traceback (most recent call last):
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/lib/python3.9/site-packages/feast/importer.py", line 26, in import_class
    module = importlib.import_module(module_name)
  File "/Users/<hidden>/.pyenv/versions/3.9.13/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/lib/python3.9/site-packages/feast/infra/offline_stores/bigquery.py", line 378, in <module>
    class BigQueryRetrievalJob(RetrievalJob):
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/lib/python3.9/site-packages/feast/infra/offline_stores/bigquery.py", line 478, in BigQueryRetrievalJob
    ) -> Optional[bigquery.job.query.QueryJob]:
AttributeError: module 'google.cloud.bigquery.job' has no attribute 'query'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/lib/python3.9/site-packages/feast/cli.py", line 517, in apply_total_command
    repo_config = load_repo_config(repo, fs_yaml_file)
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/lib/python3.9/site-packages/feast/repo_config.py", line 499, in load_repo_config
    c = RepoConfig(**raw_config)
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/lib/python3.9/site-packages/feast/repo_config.py", line 166, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 340, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1050, in pydantic.main.validate_model
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/lib/python3.9/site-packages/feast/repo_config.py", line 345, in _validate_offline_store_config
    offline_config_class = get_offline_config_from_type(offline_store_type)
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/lib/python3.9/site-packages/feast/repo_config.py", line 480, in get_offline_config_from_type
    return import_class(module_name, config_class_name, config_class_name)
  File "/Users/<hidden>/Library/Caches/pypoetry/virtualenvs/feast-example-zjuEIhwY-py3.9/lib/python3.9/site-packages/feast/importer.py", line 31, in import_class
    raise FeastModuleImportError(module_name, class_name) from e
feast.errors.FeastModuleImportError: Could not import module 'feast.infra.offline_stores.bigquery' while attempting to load class 'BigQueryOfflineStoreConfig'
```

This exception happens because Feast's `bigquery` module imports the class `google.cloud.bigquery.job.query.QueryJob`, but that path doesn't exist in the `google-cloud-bigquery 2.1.0`.

https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/offline_stores/bigquery.py#L478

```python
    @log_exceptions_and_usage
    def _execute_query(
        self, query, job_config=None, timeout: int = 1800
    ) -> Optional[bigquery.job.query.QueryJob]:
```

I was able to use Feast only when `google-cloud-bigquery` was upgraded to higher versions (e.g. `2.36.0`), but I think Feast should not allow the resolution of a dependency version that is not working properly.

## Steps to reproduce

```
poetry init -n
poetry add google-cloud-bigquery==2.1.0
poetry add --extras gcp,bigquery feast==0.24.1
```

After installing the requirements you can try to create some feature views from BQ or just check if that path exists in such version.

```
poetry run python
```
```python
>>> from google.cloud import bigquery
>>> bigquery.job.query.QueryJob
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'google.cloud.bigquery.job' has no attribute 'query'
```

### Specifications

- Version: 0.24.1 
- Platform: Python 3.9 on MacOS
- Subsystem:

## Possible Solution

This problem could possibly be solved by:

1) Increasing the minimium version allowed for this dependency
2) Changing the import statement from `google.cloud.bigquery.job.query.QueryJob` to `google.cloud.bigquery.job.QueryJob`

**Comment by sudohainguyen** [comment]
hey I have the same issue, just did a little bit deeper then I found out that Poetry picked up the lowest versions as possible compared to pinned range versions. In particular it got `google-cloud-bigquery==2.1.0` and `google-cloud-core==1.7.3`
