### ISSUE TITLE
python server's push api not work

### ISSUE THREAD

**Issue by hsz1273327** [feast-dev/feast#3307]
python server's push api notwork.

```bash
curl -X POST "http://localhost:6566/push" -d '{
    "push_source_name": "driver_stats_push_source",
    "df": {
            "driver_id": [1001],
            "event_timestamp": ["2022-05-13 10:59:42"],
            "created": ["2022-05-13 10:59:42"],
            "conv_rate": [1.0],
            "acc_rate": [1.0],
            "avg_daily_trips": [1000]
    },
    "to": "online_and_offline"
  }'
```

## Current Behavior

+ response

```json
{"detail":"Failed to parse string: '2022-05-13 10:59:42' as a scalar of type timestamp[us, tz=UTC]expected a zone offset. If these timestamps are in local time, cast to timestamp without timezone, then call assume_timezone."}%       
```

+ log

```txt
/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/infra/offline_stores/file_source.py:161: FutureWarning: 'ParquetDataset.schema' attribute is deprecated as of pyarrow 5.0.0 and will be removed in a future version. Specify 'use_legacy_dataset=False' while constructing the ParquetDataset, and then use the '.schema' attribute instead (which will return an Arrow schema instead of a Parquet schema).
  schema = ParquetDataset(path).schema.to_arrow_schema()
/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/infra/offline_stores/file_source.py:161: FutureWarning: 'ParquetDataset.schema' attribute is deprecated as of pyarrow 5.0.0 and will be removed in a future version. Specify 'use_legacy_dataset=False' while constructing the ParquetDataset, and then use the '.schema' attribute instead (which will return an Arrow schema instead of a Parquet schema).
  schema = ParquetDataset(path).schema.to_arrow_schema()
10/20/2022 05:56:58 PM fastapi ERROR: Traceback (most recent call last):
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/feature_server.py", line 96, in push
    store.push(
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/usage.py", line 283, in wrapper
    return func(*args, **kwargs)
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/feature_store.py", line 1458, in push
    self.write_to_offline_store(
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/usage.py", line 283, in wrapper
    return func(*args, **kwargs)
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/feature_store.py", line 1530, in write_to_offline_store
    provider.ingest_df_to_offline_store(feature_view, table)
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/infra/passthrough_provider.py", line 224, in ingest_df_to_offline_store
    self.offline_write_batch(self.repo_config, feature_view, table, None)
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/infra/passthrough_provider.py", line 173, in offline_write_batch
    self.offline_store.__class__.offline_write_batch(
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/infra/offline_stores/file.py", line 458, in offline_write_batch
    table = table.cast(prev_table.schema)
  File "pyarrow/table.pxi", line 3389, in pyarrow.lib.Table.cast
  File "pyarrow/table.pxi", line 523, in pyarrow.lib.ChunkedArray.cast
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/pyarrow/compute.py", line 376, in cast
    return call_function("cast", [arr], options)
  File "pyarrow/_compute.pyx", line 542, in pyarrow._compute.call_function
  File "pyarrow/_compute.pyx", line 341, in pyarrow._compute.Function.call
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Failed to parse string: '2022-05-13 10:59:42' as a scalar of type timestamp[us, tz=UTC]expected a zone offset. If these timestamps are in local time, cast to timestamp without timezone, then call assume_timezone.
Traceback (most recent call last):
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/feature_server.py", line 96, in push
    store.push(
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/usage.py", line 283, in wrapper
    return func(*args, **kwargs)
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/feature_store.py", line 1458, in push
    self.write_to_offline_store(
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/usage.py", line 283, in wrapper
    return func(*args, **kwargs)
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/feature_store.py", line 1530, in write_to_offline_store
    provider.ingest_df_to_offline_store(feature_view, table)
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/infra/passthrough_provider.py", line 224, in ingest_df_to_offline_store
    self.offline_write_batch(self.repo_config, feature_view, table, None)
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/infra/passthrough_provider.py", line 173, in offline_write_batch
    self.offline_store.__class__.offline_write_batch(
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/feast/infra/offline_stores/file.py", line 458, in offline_write_batch
    table = table.cast(prev_table.schema)
  File "pyarrow/table.pxi", line 3389, in pyarrow.lib.Table.cast
  File "pyarrow/table.pxi", line 523, in pyarrow.lib.ChunkedArray.cast
  File "/Users/mac/WORKSPACE/TEST/feast/env/lib/python3.8/site-packages/pyarrow/compute.py", line 376, in cast
    return call_function("cast", [arr], options)
  File "pyarrow/_compute.pyx", line 542, in pyarrow._compute.call_function
  File "pyarrow/_compute.pyx", line 341, in pyarrow._compute.Function.call
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Failed to parse string: '2022-05-13 10:59:42' as a scalar of type timestamp[us, tz=UTC]expected a zone offset. If these timestamps are in local time, cast to timestamp without timezone, then call assume_timezone.
```

### Specifications

- Version: 0.26.0
- Platform: macos

## Possible Solution

looks like it's a bug

**Comment by adchia** [comment]
Ah thanks for calling out that the documentation is slightly off given the `feast init` templates. Making a fix to the docs!

**Comment by shuchu** [comment]
I got the almost similar problem. After everything follow the tutorial, and run the "python3 test_workflow.py". I got the following errors:

```
--- Simulate a stream event ingestion of the hourly stats df ---
   driver_id     event_timestamp             created  conv_rate  acc_rate  avg_daily_trips
0       1001 2021-05-13 10:59:42 2021-05-13 10:59:42        1.0       1.0             1000
Traceback (most recent call last):
  File "/Users/shuchu.han/Documents/Devo/devo_feature_store/my_project/feature_repo/test_workflow.py", line 124, in <module>
    run_demo()
  File "/Users/shuchu.han/Documents/Devo/devo_feature_store/my_project/feature_repo/test_workflow.py", line 46, in run_demo
    store.push("driver_stats_push_source", event_df, to=PushMode.ONLINE_AND_OFFLINE)
  File "/Users/shuchu.han/Documents/Devo/venv3/lib/python3.9/site-packages/feast/usage.py", line 294, in wrapper
    raise exc.with_traceback(traceback)
  File "/Users/shuchu.han/Documents/Devo/venv3/lib/python3.9/site-packages/feast/usage.py", line 283, in wrapper
    return func(*args, **kwargs)
  File "/Users/shuchu.han/Documents/Devo/venv3/lib/python3.9/site-packages/feast/feature_store.py", line 1450, in push
    raise PushSourceNotFoundException(push_source_name)
feast.errors.PushSourceNotFoundException: Unable to find push source 'driver_stats_push_source'.
```
