### ISSUE TITLE
go serve never run

### ISSUE THREAD

**Issue by hsz1273327** [feast-dev/feast#3308]
### Specifications

- Version:  0.26.0
- Platform: macos

## Possible Solution

`feature_store.py`-> `class FeatureStore` ->`def serve`-> line 2275

change

```python
 if self.config.go_feature_serving and self._go_server:
```
to
```python
 if self.config.go_feature_serving and self._go_server is None:
```

**Comment by sudohainguyen** [comment]
I believe go server got deprecated due to many reasons  such as #2943

**Comment by idahoakl** [comment]
Can also confirm that golang feature server doesn't execute.  This is seen more explicitly when asking the golang server to serve in gRPC.  

```
feast serve --go --type=grpc
/opt/miniconda3/envs/feast-0.26/lib/python3.10/site-packages/feast/repo_config.py:216: RuntimeWarning: `entity_key_serialization_version` is either not specified in the feature_store.yaml, or is specified to a value <= 1.This serialization version may cause errors when trying to write fields with the `Long` data type into the online store. Specifying `entity_key_serialization_version` to 2 is recommended for new projects. 
  warnings.warn(
Traceback (most recent call last):
  File "/opt/miniconda3/envs/feast-0.26/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/opt/miniconda3/envs/feast-0.26/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/feast-0.26/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/feast-0.26/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/feast-0.26/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/feast-0.26/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/miniconda3/envs/feast-0.26/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/miniconda3/envs/feast-0.26/lib/python3.10/site-packages/feast/cli.py", line 714, in serve_command
    store.serve(host, port, type_, no_access_log, no_feature_log)
  File "/opt/miniconda3/envs/feast-0.26/lib/python3.10/site-packages/feast/feature_store.py", line 2309, in serve
    raise ValueError(
ValueError: Python server only supports 'http'. Got 'grpc' instead.
```

**Comment by judahrand** [comment]
> I believe go server got deprecated due to many reasons  such as #2943

Where was this stated?
