### ISSUE TITLE
Fetching features from offline store in MinIO bucket failed with InvalidAccessKeyId

### ISSUE THREAD

**Issue by Rainfarm** [feast-dev/feast#3374]
## Expected Behavior 
When the offline store is in a MinIO bucket, fetching historical feature should work.
## Current Behavior
The fetching of historical feature failed with the following error:
```
FS Apply done!
Fetching features...
Traceback (most recent call last):
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/s3fs/core.py", line 698, in _lsdir
    async for i in it:
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/aiobotocore/paginate.py", line 30, in __anext__
    response = await self._make_request(current_kwargs)
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/aiobotocore/client.py", line 358, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "definitions.py", line 213, in <module>
    training_df = training_data.to_df()
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/feast/infra/offline_stores/offline_store.py", line 81, in to_df
    features_df = self._to_df_internal()
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/feast/usage.py", line 287, in wrapper
    raise exc.with_traceback(traceback)
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/feast/usage.py", line 276, in wrapper
    return func(*args, **kwargs)
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/feast/infra/offline_stores/file.py", line 78, in _to_df_internal
    df = self.evaluation_function().compute()
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/feast/infra/offline_stores/file.py", line 220, in evaluate_historical_retrieval
    df_to_join = _read_datasource(feature_view.batch_source)
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/feast/infra/offline_stores/file.py", line 483, in _read_datasource
    return dd.read_parquet(data_source.path, storage_options=storage_options,)
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py", line 330, in read_parquet
    read_metadata_result = engine.read_metadata(
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/dask/dataframe/io/parquet/arrow.py", line 371, in read_metadata
    dataset_info = cls._collect_dataset_info(
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/dask/dataframe/io/parquet/arrow.py", line 847, in _collect_dataset_info
    if len(paths) == 1 and fs.isdir(paths[0]):
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/fsspec/asyn.py", line 113, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/fsspec/asyn.py", line 98, in sync
    raise return_result
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/s3fs/core.py", line 1319, in _isdir
    return bool(await self._lsdir(path))
  File "/Users/eleizhu/.pyenv/versions/3.8.12/lib/python3.8/site-packages/s3fs/core.py", line 725, in _lsdir
    raise translate_boto_error(e)
PermissionError: The AWS Access Key Id you provided does not exist in our records.
```
## Steps to reproduce
1. Deploy MinIO in Kubernetes (in k3s in local laptop)
2. Create bucket in MinIO and upload data files
3. Port-forward the MinIO service to http://localhost:9000
4. Use a Python code to initialize feature store, run the Python code in local environment
5. In the same Python code try to fetch feature when the feature store initialization is done successfully. The code `training_df = training_data.to_df()` failed with the error mentioned above. Please see the complete code below.
It is weird in the sense that the initialization of feature store succeeded without problem, but fetching feature failed with accessing problem (in `RetrievalJob.to_df()`).

Python code:
```
from feast import Entity, Feature, FeatureView, ValueType, FeatureService, PushSource
from feast.data_format import ParquetFormat, AvroFormat, ProtoFormat
from feast.infra.offline_stores.file_source import FileSource
from feast.repo_config import RegistryConfig, RepoConfig
from feast.infra.offline_stores.file import FileOfflineStoreConfig
from feast.infra.online_stores.sqlite import SqliteOnlineStoreConfig
from feast import FeatureStore
from datetime import timedelta, datetime
from google.protobuf.duration_pb2 import Duration

import os
import s3fs
import numpy as np
import pandas as pd

bucket_name = "myfeast"
df1_file_name = "data_df1.parquet"
df2_file_name = "data_df2.parquet"
df3_file_name = "data_df3.parquet"
df4_file_name = "data_df4.parquet"
target_df_file_name = "target_df.parquet"

s3_endpoint = "http://localhost:9000"

s3 = s3fs.S3FileSystem(key='minio',
                       secret='minio123',
                       client_kwargs={'endpoint_url': s3_endpoint}, use_ssl=False)

patient = Entity(
    name="patient_id", 
    value_type=ValueType.INT64, 
    description="The ID of the patient")

# Declaring the source of the first set of features
f_source1 = FileSource(
    path=f"s3://{bucket_name}/{df1_file_name}",
    timestamp_field="event_timestamp",
    created_timestamp_column="created",
)
# Defining the first set of features
df1_fv = FeatureView(
    name="df1_feature_view",
    ttl=Duration(seconds=86400 * 3),
    entities=["patient_id"],
    features=[
        Feature(name="created", dtype=ValueType.STRING),
        Feature(name="mean radius", dtype=ValueType.FLOAT),
        Feature(name="mean texture", dtype=ValueType.FLOAT),
        Feature(name="mean perimeter", dtype=ValueType.FLOAT),
        Feature(name="mean area", dtype=ValueType.FLOAT),
        Feature(name="mean smoothness", dtype=ValueType.FLOAT)
        ],    
    batch_source=f_source1
)

# Declaring the source of the second set of features
f_source2 = FileSource(
    path=f"s3://{bucket_name}/{df2_file_name}",
    timestamp_field="event_timestamp",
    created_timestamp_column="created",
)

# Defining the second set of features
df2_fv = FeatureView(
    name="df2_feature_view",
    ttl=Duration(seconds=86400 * 3),
    entities=["patient_id"],
    features=[
        Feature(name="mean compactness", dtype=ValueType.FLOAT),
        Feature(name="mean concavity", dtype=ValueType.FLOAT),
        Feature(name="mean concave points", dtype=ValueType.FLOAT),
        Feature(name="mean symmetry", dtype=ValueType.FLOAT),
        Feature(name="mean fractal dimension", dtype=ValueType.FLOAT)
        ],    
    batch_source=f_source2
)

# Declaring the source of the third set of features
f_source3 = FileSource(
    path=f"s3://{bucket_name}/{df3_file_name}",
    timestamp_field="event_timestamp",
    created_timestamp_column="created",
)

# Defining the third set of features
df3_fv = FeatureView(
    name="df3_feature_view",
    ttl=Duration(seconds=86400 * 3),
    entities=["patient_id"],
    features=[
        Feature(name="radius error", dtype=ValueType.FLOAT),
        Feature(name="texture error", dtype=ValueType.FLOAT),
        Feature(name="perimeter error", dtype=ValueType.FLOAT),
        Feature(name="area error", dtype=ValueType.FLOAT),
        Feature(name="smoothness error", dtype=ValueType.FLOAT),
        Feature(name="compactness error", dtype=ValueType.FLOAT),
        Feature(name="concavity error", dtype=ValueType.FLOAT)
        ],    
    batch_source=f_source3
)

# Declaring the source of the fourth set of features
f_source4 = FileSource(
    path=f"s3://{bucket_name}/{df4_file_name}",
    timestamp_field="event_timestamp",
    created_timestamp_column="created",
)

# Defining the fourth set of features
df4_fv = FeatureView(
    name="df4_feature_view",
    ttl=Duration(seconds=86400 * 3),
    entities=["patient_id"],
    features=[
        Feature(name="concave points error", dtype=ValueType.FLOAT),
        Feature(name="symmetry error", dtype=ValueType.FLOAT),
        Feature(name="fractal dimension error", dtype=ValueType.FLOAT),
        Feature(name="worst radius", dtype=ValueType.FLOAT),
        Feature(name="worst texture", dtype=ValueType.FLOAT),
        Feature(name="worst perimeter", dtype=ValueType.FLOAT),
        Feature(name="worst area", dtype=ValueType.FLOAT),
        Feature(name="worst smoothness", dtype=ValueType.FLOAT),
        Feature(name="worst compactness", dtype=ValueType.FLOAT),
        Feature(name="worst concavity", dtype=ValueType.FLOAT),
        Feature(name="worst concave points", dtype=ValueType.FLOAT),
        Feature(name="worst symmetry", dtype=ValueType.FLOAT),
        Feature(name="worst fractal dimension", dtype=ValueType.FLOAT),        
        ],    
    batch_source=f_source4
)

# Declaring the source of the targets
target_source = FileSource(
    path=f"s3://{bucket_name}/{target_df_file_name}",
    timestamp_field="event_timestamp",
    created_timestamp_column="created",
)

# Defining the targets
target_fv = FeatureView(
    name="target_feature_view",
    entities=["patient_id"],
    ttl=Duration(seconds=86400 * 3),
    features=[
        Feature(name="target", dtype=ValueType.INT32)        
        ],    
    batch_source=target_source
)

registry_path = 'registry.db'
os.environ["FEAST_S3_ENDPOINT_URL"] = s3_endpoint
os.environ["AWS_ACCESS_KEY_ID"] = "minio"
os.environ["AWS_SECRET_ACCESS_KEY"] = "minio123"

repo = RepoConfig(
            registry=f"s3://{bucket_name}/{registry_path}",
            project='myfeast',
            provider="local",
            offline_store="file",
            #online_store=SqliteOnlineStoreConfig(),
            use_ssl=False, #True, 
            filesystem=s3,
            is_secure=False, #True,
            validate=False, #True,
)

fs = FeatureStore(config=repo)

fs.apply([df1_fv, df2_fv, df3_fv, df4_fv, target_fv, patient])
#fs.apply([df1_fv, patient])

print("FS Apply done!")
print("Fetching features...")

entity_df = pd.read_parquet(path="data/target_df.parquet")
# Retrieving historical features
training_data = fs.get_historical_features(
    entity_df=entity_df,
    features=[
        "df1_feature_view:mean radius",
        "df1_feature_view:mean texture",
        "df1_feature_view:mean perimeter",
        "df1_feature_view:mean area",
        "df1_feature_view:mean smoothness",
        "df2_feature_view:mean compactness",
        "df2_feature_view:mean concavity",
        "df2_feature_view:mean concave points",
        "df2_feature_view:mean symmetry",
        "df2_feature_view:mean fractal dimension",
        "df3_feature_view:radius error",
        "df3_feature_view:texture error",
        "df3_feature_view:perimeter error",
        "df3_feature_view:area error",
        "df3_feature_view:smoothness error",
        "df3_feature_view:compactness error",
        "df3_feature_view:concavity error",
        "df4_feature_view:concave points error",
        "df4_feature_view:symmetry error",
        "df4_feature_view:fractal dimension error",
        "df4_feature_view:worst radius",
        "df4_feature_view:worst texture",
        "df4_feature_view:worst perimeter",
        "df4_feature_view:worst area",
        "df4_feature_view:worst smoothness",
        "df4_feature_view:worst compactness",
        "df4_feature_view:worst concavity",
        "df4_feature_view:worst concave points",
        "df4_feature_view:worst symmetry",
        "df4_feature_view:worst fractal dimension"
    ]
)

training_df = training_data.to_df()
```
### Specifications

- Version:
feast==0.22.4
s3fs==2022.11.0
MinIO: RELEASE.2019-08-14T20-37-41Z-license-compliance
- Platform:
k3s (Rancher) in MacOS
- Subsystem:

**Comment by Leumastai** [comment]
@Rainfarm where you able to resolve the error?
