### ISSUE TITLE
Jupyter Notebook Feast apply should ignore .ipynb_checkpoints

### ISSUE THREAD

**Issue by szymonbcoding** [feast-dev/feast#3474]
**Is your feature request related to a problem? Please describe.**
I had problem with using Feast with Jupyter Sever on my Kubeflow platform. I prepared my feast-ish definitions and got error:
```
Traceback (most recent call last):
  File "/opt/conda/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/feast/cli.py", line 519, in apply_total_command
    apply_total(repo_config, repo, skip_source_validation)
  File "/opt/conda/lib/python3.8/site-packages/feast/usage.py", line 299, in wrapper
    raise exc.with_traceback(traceback)
  File "/opt/conda/lib/python3.8/site-packages/feast/usage.py", line 288, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/feast/repo_operations.py", line 334, in apply_total
    project, registry, repo, store = _prepare_registry_and_repo(repo_config, repo_path)
  File "/opt/conda/lib/python3.8/site-packages/feast/repo_operations.py", line 233, in _prepare_registry_and_repo
    repo = parse_repo(repo_path)
  File "/opt/conda/lib/python3.8/site-packages/feast/repo_operations.py", line 119, in parse_repo
    module = importlib.import_module(module_path)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.ipynb_checkpoints.extra_repo-checkpoint'
```
during executing command
```
feast apply
```

I realised that in _feature_repo_ is hidden directory  _.ipynb_checkpoints_  which is cause of problem. 
After deleting it, my problem have gone.

**Describe the solution you'd like**
Feast during executing command:
```
feast apply
```
should ignore hidden directory _.ipynb_checkpoints_

**Comment by JustasB** [comment]
Same issue here, deleting `.ipynb_checkpoints` folder fixed the error message.

**Comment by JustasB** [comment]
Should be able to use the `.feastignore` file to ignore the jupyter files

See: https://docs.feast.dev/reference/feature-repository/feast-ignore
