### ISSUE TITLE
feature_service_proto.spec.project has None value

### ISSUE THREAD

**Issue by goodseog** [feast-dev/feast#3486]
## Expected Behavior 
Returns correct online feature values without error.

## Current Behavior
```store.get_online_store``` doens't work with ```feature_service_proto.spec.project```.

## Steps to reproduce
With ```feature_store.yaml```
```yaml
project: gfa_data_dev
provider: local
registry: 
  registry_type: sql
  path: "postgresql://-"
  cache_ttl_seconds: 600 # 10 minutes
offline_store:
  type: file
online_store:
  type: redis
  key_ttl_seconds: 1209600 # 14 days
  connection_string: "-:6379"
entity_key_serialization_version: 2

```

It was confirmed that ```fs.get_feature_service``` and ```fs.get_offline_features``` work properly.
```python
features = store.get_feature_service("driver_activity")
print(features)
{
  "spec": {
    "name": "driver_activity",
    "features": [
      {
        "featureViewName": "driver_hourly_stats",
        "featureColumns": [
          {
            "name": "conv_rate",
            "valueType": "FLOAT"
          },
          {
            "name": "acc_rate",
            "valueType": "FLOAT"
          },
          {
            "name": "avg_daily_trips",
            "valueType": "INT64"
          }
        ]
      }
    ]
  },
  "meta": {
    "createdTimestamp": "2023-02-10T07:04:18.961213Z",
    "lastUpdatedTimestamp": "2023-02-10T07:04:18.961213Z"
  }
}

print(
    store.get_historical_features(
        entity_df=pd.DataFrame(
            [
                {"driver_id": 1001, "event_timestamp": pd.Timestamp.now(tz="Asia/Seoul")},
                {"driver_id": 1002, "event_timestamp": pd.Timestamp.now(tz="Asia/Seoul")},
                {"driver_id": 1003, "event_timestamp": pd.Timestamp.now(tz="Asia/Seoul")},
                {"driver_id": 1004, "event_timestamp": pd.Timestamp.now(tz="Asia/Seoul")}
            ]
        ),
        features=features,
    ).to_df()
)
   driver_id                  event_timestamp  conv_rate  acc_rate  avg_daily_trips
0       1003 2023-02-10 07:13:00.889649+00:00   0.334395  0.998455              576
1       1002 2023-02-10 07:13:00.889628+00:00   0.046236  0.256595               71
2       1004 2023-02-10 07:13:00.889662+00:00   0.206959  0.146476              936
3       1001 2023-02-10 07:13:00.889242+00:00   0.341070  0.323111              914
```

But ```store.get_online_features``` doesn't work with error
```python

print(
    store.get_online_features(
        features=features,
        entity_rows=[{"driver": 1001}, {"driver": 1002},]
    ).to_dict()
)
```
```
Traceback (most recent call last):
  File "/home1/irteam/notebooks/git/pa-dmp-feast/stage/example.py", line 27, in <module>
    store.get_online_features(
  File "/home1/irteam/miniconda3/envs/feast/lib/python3.9/site-packages/feast/usage.py", line 288, in wrapper
    return func(*args, **kwargs)
  File "/home1/irteam/miniconda3/envs/feast/lib/python3.9/site-packages/feast/feature_store.py", line 1591, in get_online_features
    return self._get_online_features(
  File "/home1/irteam/miniconda3/envs/feast/lib/python3.9/site-packages/feast/feature_store.py", line 1654, in _get_online_features
    _feature_refs = self._get_features(features, allow_cache=True)
  File "/home1/irteam/miniconda3/envs/feast/lib/python3.9/site-packages/feast/feature_store.py", line 526, in _get_features
    feature_service_from_registry = self.get_feature_service(
  File "/home1/irteam/miniconda3/envs/feast/lib/python3.9/site-packages/feast/usage.py", line 299, in wrapper
    raise exc.with_traceback(traceback)
  File "/home1/irteam/miniconda3/envs/feast/lib/python3.9/site-packages/feast/usage.py", line 288, in wrapper
    return func(*args, **kwargs)
  File "/home1/irteam/miniconda3/envs/feast/lib/python3.9/site-packages/feast/feature_store.py", line 388, in get_feature_service
    return self._registry.get_feature_service(name, self.project, allow_cache)
  File "/home1/irteam/miniconda3/envs/feast/lib/python3.9/site-packages/feast/infra/registry/sql.py", line 359, in get_feature_service
    return proto_registry_utils.get_feature_service(
  File "/home1/irteam/miniconda3/envs/feast/lib/python3.9/site-packages/feast/infra/registry/proto_registry_utils.py", line 33, in get_feature_service
    raise FeatureServiceNotFoundException(name, project=project)
feast.errors.FeatureServiceNotFoundException: Feature service driver_activity does not exist in project gfa_data_dev
```

Of course it materialized by cli like
```bash
(feast) [user@host stage]$ feast materialize-incremental 2023-02-10T16:00:00+09:00
Materializing 1 feature views to 2023-02-10 16:00:00+09:00 into the redis online store.

driver_hourly_stats from 2023-01-11 07:09:56+09:00 to 2023-02-10 16:00:00+09:00:
02/10/2023 04:09:56 PM aiobotocore.credentials INFO: Found credentials in environment variables.
10it [00:00, 1968.05it/s]                                                                       
```
<img width="357" alt="image" src="https://user-images.githubusercontent.com/24894273/218028609-3d777f90-afc7-4461-b44f-3683e50aec15.png">

For debugging, add a print statement to the source code, 
and through the results below, I found that the value was not entered into ```feature_service_proto.spec.project```.
```python
def get_feature_service(
    registry_proto: RegistryProto, name: str, project: str
) -> FeatureService:
    for feature_service_proto in registry_proto.feature_services:
        # DEBUG PRINT for spec.project
        print(f"proj: {feature_service_proto.spec.project}, name: {feature_service_proto.spec.name}")
        if (
            feature_service_proto.spec.project == project
            and feature_service_proto.spec.name == name
        ):
            return FeatureService.from_proto(feature_service_proto)
    raise FeatureServiceNotFoundException(name, project=project)

# Print result
proj: , name: driver_activity
```

### Specifications

- Version: 0.29.0
- Platform: CentOS7
- Subsystem: 
- Python : miniconda, python 3.9.12
- Python Packages:
  - feast                    0.29.0
  - hiredis                  2.2.1
  - psycopg2                 2.9.5
  - psycopg2-binary          2.9.5
  - redis                    4.2.2
  - googleapis-common-protos 1.58.0
  - proto-plus               1.22.2
  - protobuf                 4.21.12

## Possible Solution
- protobuf issue?
- OS Issue? or conda / pip install issue?

**Comment by job-almekinders** [comment]
Hey @goodseog, I'm running into the same issue now, using feast=0.36.0. 

Did you find any solution to this problem?
