### ISSUE TITLE
Postgresql support for the Registry

### ISSUE THREAD

**Issue by unencoded** [feast-dev/feast#3487]
## Expected Behavior 
Postgresql as a storage for the Registry
## Current Behavior
feast-feature-server crash with the error 
```
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: RuntimeException: Registry storage postgresql is unsupported
  at RegistryConfigModule.registryFile(RegistryConfigModule.java:52)
  at RegistryConfigModule.registryRepository(RegistryConfigModule.java:72)
      \_ for 1st parameter
  at RegistryConfigModule.registryRepository(RegistryConfigModule.java:72)
  at ServingServiceV2Module.registryBasedServingServiceV2(ServingServiceV2Module.java:40)
      \_ for 2nd parameter
  at ServingServiceV2Module.registryBasedServingServiceV2(ServingServiceV2Module.java:40)
  at OnlineServingGrpcServiceV2.<init>(OnlineServingGrpcServiceV2.java:33)
      \_ for 1st parameter
  at ServerModule.provideGrpcServer(ServerModule.java:43)
      \_ for 2nd parameter
  at ServerModule.provideGrpcServer(ServerModule.java:43)
  while locating Server

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER
```
Also confusing this doc https://docs.feast.dev/tutorials/using-scalable-registry 

## Steps to reproduce
Try to deploy Feast via Helm from the feast-charts/feast with the next values
```
global:
  registry:
    registry_type: sql
    path: "postgresql://postgres:password@feast-aurora.cluster-**.rds.amazonaws.com/postgres"
  project: feast_demo
feature-server:
  application-override.yaml:
      enabled: true
      feast:
          active_store: online
          stores:
          - name: online
            type: REDIS
            config:
              host: feast-elasticache.***.cache.amazonaws.com
              port: 6379
          - name: offline
            type: postgres
            config:
              host: feast-aurora.cluster-**.rds.amazonaws.com
              port: 5432
              database: postgres
              db_schema: public
              user: postgresql
              password: password
          entityKeySerializationVersion: 2

```

### Specifications

- Version: [Helm Chart v0.29](https://github.com/feast-dev/feast/tree/master/infra/charts/feast)
- Platform: AWS
- Subsystem: EKS

## Possible Solution
As I understand, according to the source code of the registry.py, postgres as a storage for the Registry can't work.  
https://github.com/feast-dev/feast/blob/2f7c4ede8f9e66703714261f1152f78526d4bf43/sdk/python/feast/infra/registry/registry.py#L57-L70

**Comment by jeremyary** [comment]
Postgres can now be used to back Registry. Currently, Postgres has it's [own](https://github.com/feast-dev/feast/issues/4020) mechanism, but will likely be merged with SQLAlchemy support in the near future.
