### ISSUE TITLE
Get error "TypeError: cannot create weak reference to 'property' object" when I do feast apply

### ISSUE THREAD

**Issue by MinfangTao** [feast-dev/feast#3539]
## Current Behavior
 feast apply
Traceback (most recent call last):
  File "/feast/venv/bin/feast", line 33, in <module>
    sys.exit(load_entry_point('feast==0.29.0', 'console_scripts', 'feast')())
  File "/feast/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/feast/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/feast/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/feast/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/feast/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/feast/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/feast/venv/lib/python3.10/site-packages/feast-0.29.0-py3.10-linux-x86_64.egg/feast/cli.py", line 532, in apply_total_command
    apply_total(repo_config, repo, skip_source_validation)
  File "/feast/venv/lib/python3.10/site-packages/feast-0.29.0-py3.10-linux-x86_64.egg/feast/usage.py", line 299, in wrapper
    raise exc.with_traceback(traceback)
  File "/feast/venv/lib/python3.10/site-packages/feast-0.29.0-py3.10-linux-x86_64.egg/feast/usage.py", line 288, in wrapper
    return func(*args, **kwargs)
  File "/feast/venv/lib/python3.10/site-packages/feast-0.29.0-py3.10-linux-x86_64.egg/feast/repo_operations.py", line 334, in apply_total
    project, registry, repo, store = _prepare_registry_and_repo(repo_config, repo_path)
  File "/feast/venv/lib/python3.10/site-packages/feast-0.29.0-py3.10-linux-x86_64.egg/feast/repo_operations.py", line 233, in _prepare_registry_and_repo
    repo = parse_repo(repo_path)
  File "/feast/venv/lib/python3.10/site-packages/feast-0.29.0-py3.10-linux-x86_64.egg/feast/repo_operations.py", line 119, in parse_repo
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mytest/feature_repo/example_repo.py", line 88, in <module>
    driver_stats_fv[["conv_rate"]],  # Sub-selects a feature from a feature view
  File "/feast/venv/lib/python3.10/site-packages/feast-0.29.0-py3.10-linux-x86_64.egg/feast/base_feature_view.py", line 118, in __getitem__
    cp = self.__copy__()
  File "/feast/venv/lib/python3.10/site-packages/feast-0.29.0-py3.10-linux-x86_64.egg/feast/feature_view.py", line 222, in __copy__
    schema=self.schema,
  File "/feast/venv/lib/python3.10/site-packages/feast-0.29.0-py3.10-linux-x86_64.egg/feast/feature_view.py", line 261, in schema
    def schema(self) -> List[Field]:
  File "/feast/venv/lib/python3.10/site-packages/typeguard/_memo.py", line 70, in __init__
    self.type_hints = _type_hints_map[func]
  File "/usr/local/lib/python3.10/weakref.py", line 416, in __getitem__
    return self.data[ref(key)]
TypeError: cannot create weak reference to 'property' object
(venv) root@cb77bd531331:/mytest/feature_repo# 

## Steps to reproduce
Following README.md:
pip install feast
feast init mytest
cd mytest/feature_repo/
feast apply/plan

env: Windows 11 + Docker , Python 3.9 and 3.10 
### Specifications

- Version:
0.29
- Platform:
 Windows 11 + Docker
- Subsystem:
 Python 3.9 and 3.10

**Comment by diegofjb** [comment]
Try with this: https://github.com/feast-dev/feast/issues/3538

**Comment by diefergil** [comment]
Try with this: https://github.com/feast-dev/feast/issues/3538
