### ISSUE TITLE
postgres template breaks 

### ISSUE THREAD

**Issue by ZAn-next** [feast-dev/feast#3673]
## Expected Behavior 
run template `feast init -t postgres` without error 

## Current Behavior
with error 
` File "/<>/python3.9/site-packages/feast/infra/offline_stores/offline_store.py", line 380, in offline_write_batch
    raise NotImplementedError()
NotImplementedError` 

## Steps to reproduce
- install feast 
- run `feast init -t postgres` template

### Specifications

- Version: 0.30.0
- Platform: python 3.9.13
- Subsystem:

## Possible Solution
implement `offline_write_batch`, similar issue created before
https://github.com/feast-dev/feast/issues/3347

**Comment by shuchu** [comment]
I tried to reproduce this error but fail. Do you mind to provide more details? 

this is my logs:
`(.venv) ubuntu➜~/feast_demo/issue3673» feast init -t postgres                                                [21:19:25]
Postgres host [localhost]:
Postgres port [5432]:
Postgres DB name [postgres]:
Postgres schema [public]:
Postgres user:
Postgres user:
Postgres user:
Postgres user:
Postgres user:
Postgres user: postgres
Postgres password:
Should I upload example data to Postgres (overwriting "feast_driver_hourly_stats" table)? [Y/n]: n

Creating a new Feast repository in /home/ubuntu/feast_demo/issue3673/eager_mackerel.`

**Comment by JustasB** [comment]
@shuchu 

Steps to reproduce:

`feast init -t postgres my_store`
`cd my_store/feature_repo`
`python test_workflow.py`

The first few steps of the python script succeed, but the following step fails:
```
...
--- Simulate a stream event ingestion of the hourly stats df ---
   driver_id            event_timestamp                    created  conv_rate  acc_rate  avg_daily_trips
0       1001 2023-08-02 14:28:34.074646 2023-08-02 14:28:34.074650        1.0       1.0             1000
Traceback (most recent call last):
  File "/src/my_store/feature_repo/test_workflow.py", line 130, in <module>
    run_demo()
  File "/src/my_store/feature_repo/test_workflow.py", line 51, in run_demo
    store.push("driver_stats_push_source", event_df, to=PushMode.ONLINE_AND_OFFLINE)
  File "/opt/conda/lib/python3.11/site-packages/feast/usage.py", line 288, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/feast/feature_store.py", line 1453, in push
    self.write_to_offline_store(
  File "/opt/conda/lib/python3.11/site-packages/feast/usage.py", line 288, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/feast/feature_store.py", line 1525, in write_to_offline_store
    provider.ingest_df_to_offline_store(feature_view, table)
  File "/opt/conda/lib/python3.11/site-packages/feast/infra/passthrough_provider.py", line 224, in ingest_df_to_offline_store
    self.offline_write_batch(self.repo_config, feature_view, table, None)
  File "/opt/conda/lib/python3.11/site-packages/feast/infra/passthrough_provider.py", line 173, in offline_write_batch
    self.offline_store.__class__.offline_write_batch(
  File "/opt/conda/lib/python3.11/site-packages/feast/infra/offline_stores/offline_store.py", line 380, in offline_write_batch
    raise NotImplementedError()
NotImplementedError
```

**Comment by redhatHameed** [comment]
I have and able to create the [feast project with postgres ](https://github.com/RHEcosystemAppEng/feast-workshop-team-share/tree/main/feast_postgres#2-create-a-feature-repository)template it works without issue.

**Comment by jeremyary** [comment]
Thanks for verifying @redhatHameed :+1: considering the issue resolved
