### ISSUE TITLE
quickstart python test_workflow.py is missing _sqlite3

### ISSUE THREAD

**Issue by tbolind** [feast-dev/feast#3689]
I am testing out feast on a virtual ubuntu server, and I am following the quickstart, but when I get to the part where I have to run 
`python test_workflow.py` I get the following error:
```
(virtual_env_feast) dev@vmlcubutm01:~/feast/my_project/feature_repo$ python test_workflow.py
Traceback (most recent call last):
  File "/home/dev/feast/virtual_env_feast/lib/python3.8/site-packages/feast/importer.py", line 26, in import_class
    module = importlib.import_module(module_name)
  File "/home/dev/.pyenv/versions/3.8.17/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dev/feast/virtual_env_feast/lib/python3.8/site-packages/feast/infra/online_stores/sqlite.py", line 16, in <module>
    import sqlite3
  File "/home/dev/.pyenv/versions/3.8.17/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/home/dev/.pyenv/versions/3.8.17/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_workflow.py", line 130, in <module>
    run_demo()
  File "test_workflow.py", line 11, in run_demo
    store = FeatureStore(repo_path=".")
  File "/home/dev/feast/virtual_env_feast/lib/python3.8/site-packages/feast/usage.py", line 362, in wrapper
    raise exc.with_traceback(traceback)
  File "/home/dev/feast/virtual_env_feast/lib/python3.8/site-packages/feast/usage.py", line 348, in wrapper
    return func(*args, **kwargs)
  File "/home/dev/feast/virtual_env_feast/lib/python3.8/site-packages/feast/feature_store.py", line 154, in __init__
    self.config = load_repo_config(
  File "/home/dev/feast/virtual_env_feast/lib/python3.8/site-packages/feast/repo_config.py", line 549, in load_repo_config
    c = RepoConfig(**raw_config)
  File "/home/dev/feast/virtual_env_feast/lib/python3.8/site-packages/feast/repo_config.py", line 185, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1050, in pydantic.main.validate_model
  File "/home/dev/feast/virtual_env_feast/lib/python3.8/site-packages/feast/usage.py", line 362, in wrapper
    raise exc.with_traceback(traceback)
  File "/home/dev/feast/virtual_env_feast/lib/python3.8/site-packages/feast/usage.py", line 348, in wrapper
    return func(*args, **kwargs)
  File "/home/dev/feast/virtual_env_feast/lib/python3.8/site-packages/feast/repo_config.py", line 347, in _validate_online_store_config
    online_config_class = get_online_config_from_type(online_store_type)
  File "/home/dev/feast/virtual_env_feast/lib/python3.8/site-packages/feast/repo_config.py", line 519, in get_online_config_from_type
    return import_class(module_name, config_class_name, config_class_name)
  File "/home/dev/feast/virtual_env_feast/lib/python3.8/site-packages/feast/importer.py", line 31, in import_class
    raise FeastModuleImportError(module_name, class_name) from e
feast.errors.FeastModuleImportError: Could not import module 'feast.infra.online_stores.sqlite' while attempting to load class 'SqliteOnlineStoreConfig'
```

## Steps to reproduce
Follow the guide on https://docs.feast.dev/getting-started/quickstart, 

### Specifications
Ubuntu 22.04.2 LTS

## Possible Solution
I'm guessing I need to install sqlite3, however I tried to install it using sudo apt-install sqlite3, but that doesn't help with me needing it in python.

**Comment by tbolind** [comment]
I tried with a new virtual environment with a later version of python (3.11.4) and that resolved all the issues.
