### ISSUE TITLE
Issue with Postgres offlinestore in aws provider

### ISSUE THREAD

**Issue by shyamalshivam** [feast-dev/feast#3859]
Can anyone help in resolving below error 

Traceback (most recent call last):
  File "C:\Users\sanjaysoni\Projects\Genome\env\lib\site-packages\feast\repo_config.py", line 353, in load_repo_config     
    c = RepoConfig(**raw_config)
  File "C:\Users\sanjaysoni\Projects\Genome\env\lib\site-packages\feast\repo_config.py", line 118, in __init__
    super().__init__(**data)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for RepoConfig
__root__
   (type=assertion_error)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "C:\Users\sanjaysoni\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sanjaysoni\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sanjaysoni\Projects\Genome\env\Scripts\feast.exe\__main__.py", line 7, in <module>
  File "C:\Users\sanjaysoni\Projects\Genome\env\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\sanjaysoni\Projects\Genome\env\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\sanjaysoni\Projects\Genome\env\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\sanjaysoni\Projects\Genome\env\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\sanjaysoni\Projects\Genome\env\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\sanjaysoni\Projects\Genome\env\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\sanjaysoni\Projects\Genome\env\lib\site-packages\feast\cli.py", line 448, in apply_total_command
    repo_config = load_repo_config(repo)
  File "C:\Users\sanjaysoni\Projects\Genome\env\lib\site-packages\feast\repo_config.py", line 357, in load_repo_config     
    raise FeastConfigError(e, config_path)
feast.repo_config.FeastConfigError: 1 validation error for RepoConfig
__root__
   (type=assertion_error)
at C:\Users\sanjaysoni\Projects\Genome\feast_demo\feast\needed_ray\feature_repo\feature_store.yaml

Here is the feature_store settings
project: needed_ray
provider: aws
registry:
    path: s3://aws-landing-zone/feast_repo/registry.db
online_store: null
offline_store:
    type: postgres
    host: localhost
    port: 5432
    database: postgres
    db_schema: public
    user: admin
    password: admin
entity_key_serialization_version: 2

**Comment by redhatHameed** [comment]
@shyamalshivam are you still facing this issue ? I can try to reproduce it if you still need help.
