### ISSUE TITLE
hashlib.md5 errors in FIPS mode for Python3.9+

### ISSUE THREAD

**Issue by dawid-laszuk-sp** [feast-dev/feast#4015]
## Expected Behavior 

Initiating the server should succeed.

## Current Behavior

Getting an error

```
Traceback (most recent call last):
  File "/root/.local/bin/feast", line 5, in <module>
    from feast.cli import cli
  File "/root/.local/lib/python3.10/site-packages/feast/__init__.py", line 7, in <module>
    from feast.infra.offline_stores.bigquery_source import BigQuerySource
  File "/root/.local/lib/python3.10/site-packages/feast/infra/offline_stores/bigquery_source.py", line 6, in <module>
    from feast.data_source import DataSource
  File "/root/.local/lib/python3.10/site-packages/feast/data_source.py", line 28, in <module>
    from feast.repo_config import RepoConfig, get_data_source_class_from_type
  File "/root/.local/lib/python3.10/site-packages/feast/repo_config.py", line 29, in <module>
    from feast.usage import log_exceptions
  File "/root/.local/lib/python3.10/site-packages/feast/usage.py", line 50, in <module>
    "env_signature": hashlib.md5(
ValueError: [digital envelope routines] unsupported
```

## Steps to reproduce

I'm honestly not sure how to enable FIPS mode. We're using Amazon Linux 2023 image and it could be 

### Specifications

- Version: latest
- Platform: 
- Subsystem:

## Possible Solution

Allow passing `usedforsecurity` parameter for the [hashlib.md5](https://docs.python.org/3/library/hashlib.html#hashlib.md5) method. Here's an example of similar approach in [pytest-dev/pytest-randomly](https://github.com/pytest-dev/pytest-randomly/pull/415/files).

**Comment by jeremyary** [comment]
addressed via PR #4019. Thanks!
