### ISSUE TITLE
feast gcp notebook, getting TypeError: Client.__init__() got an unexpected keyword argument 'database'

### ISSUE THREAD

**Issue by amirali-shfz** [feast-dev/feast#4301]
## Expected Behavior 
I'm following this collab notebook and facing an error when I run `! feast apply`

https://colab.research.google.com/github/feast-dev/feast-fraud-tutorial/blob/master/notebooks/Fraud_Detection_Tutorial.ipynb

## Current Behavior

```
/usr/local/lib/python3.10/dist-packages/jupyter_client/connect.py:28: DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs
given by the platformdirs library.  To remove this warning and
see the appropriate new directories, set the environment variable
`JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
The use of platformdirs will be the default in `jupyter_core` v6
  from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
/usr/local/lib/python3.10/dist-packages/feast/repo_config.py:234: RuntimeWarning: `entity_key_serialization_version` is either not specified in the feature_store.yaml, or is specified to a value <= 1.This serialization version may cause errors when trying to write fields with the `Long` data type into the online store. Specifying `entity_key_serialization_version` to 2 is recommended for new projects. 
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/feast/feature_store.py:534: RuntimeWarning: On demand feature view is an experimental feature. This API is stable, but the functionality does not scale well for offline retrieval
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/feast/cli.py", line 489, in apply_total_command
    apply_total(repo_config, repo, skip_source_validation)
  File "/usr/local/lib/python3.10/dist-packages/feast/repo_operations.py", line 347, in apply_total
    apply_total_with_repo_instance(
  File "/usr/local/lib/python3.10/dist-packages/feast/repo_operations.py", line 305, in apply_total_with_repo_instance
    store.apply(all_to_apply, objects_to_delete=all_to_delete, partial=False)
  File "/usr/local/lib/python3.10/dist-packages/feast/feature_store.py", line 938, in apply
    self._get_provider().update_infra(
  File "/usr/local/lib/python3.10/dist-packages/feast/infra/passthrough_provider.py", line 117, in update_infra
    self.online_store.update(
  File "/usr/local/lib/python3.10/dist-packages/feast/infra/online_stores/datastore.py", line 117, in update
    client = self._get_client(online_config)
  File "/usr/local/lib/python3.10/dist-packages/feast/infra/online_stores/datastore.py", line 159, in _get_client
    self._client = _initialize_client(
  File "/usr/local/lib/python3.10/dist-packages/feast/infra/online_stores/datastore.py", line 351, in _initialize_client
    client = datastore.Client(
TypeError: Client.__init__() got an unexpected keyword argument 'database'
```
## Steps to reproduce
Run everything up until the first `! feast apply` command in the notebook. Note that I am providing real projects/bucket/etc.
### Specifications

- Version: 0.39.0 and 0.38.0
- Platform: collab on gcs
- Subsystem:

**Comment by amirali-shfz** [comment]
duplicates https://github.com/feast-dev/feast/issues/4314
