### ISSUE TITLE
Deprecation of distutils in python 3.12 breaking feast init

### ISSUE THREAD

**Issue by danbaron63** [feast-dev/feast#4341]
## Expected Behavior 
`feast init` should execute successfully.

## Current Behavior
`feast init` fails with the following error:
```
$ feast init my_project
Traceback (most recent call last):
  File "/Users/xxx/code/feast-demo/.venv/bin/feast", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/xxx/code/feast-demo/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/code/feast-demo/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/xxx/code/feast-demo/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/code/feast-demo/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/code/feast-demo/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/code/feast-demo/.venv/lib/python3.12/site-packages/feast/cli.py", line 629, in init_command
    init_repo(project_directory, template)
  File "/Users/xxx/code/feast-demo/.venv/lib/python3.12/site-packages/feast/repo_operations.py", line 379, in init_repo
    from distutils.dir_util import copy_tree
ModuleNotFoundError: No module named 'distutils'
```

## Steps to reproduce
Install python 3.12 (with pyenv or other):
```
pyenv local 3.12
```
Install feast using pip in a venv
```
python -m venv .venv
source .venv/bin/activate
pip install feast==0.39.1
```
Run `feast init`:
```
feast init my_project
```

### Specifications

- Version: 0.39.1
- Platform: macOS Sonoma, Version 14.5, Apple M1 Max, Python 3.12.4
- Subsystem: ?

## Possible Solution
Distribute with `setuptools` or follow the migration advice in [PEP 632](https://peps.python.org/pep-0632/)

Thanks!

**Comment by tokoko** [comment]
I removed `distutils`, but we're still not testing 3.12 in ci, so there might be other problems.
