### ISSUE TITLE
Bug: `ModuleNotFoundError: No module named 'feast_trino'` error when running `feast apply` setting OfflineStore as trino

### ISSUE THREAD

**Issue by younghun-jo119** [feast-dev/feast#4728]
## Expected Behavior 

I will use feast python feature server using Offline store as trino and Online store as redis. I followed official docs guide of using trino as offline store. I installed command `pip install feast[trino]` but I checked `pip list `, there is no package related to trino.

But I got this error about modue not found `feast_trino`. The details of error is below.
```
Traceback (most recent call last):
  File "/Users/zedd/.pyenv/versions/3.11.10/envs/data-mlops-feast/lib/python3.11/site-packages/feast/importer.py", line 26, in import_class
    module = importlib.import_module(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zedd/.pyenv/versions/3.11.10/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'feast_trino'
```

### Specifications

- Version: 0.41.3
- Platform: MacOS arm64(M3 pro), Ubnutu
- Subsystem:

**Comment by younghun-jo119** [comment]
I solved it. The docs is not updated lately...
