### ISSUE TITLE
Kubernetes authz throws an error when using "feastdev/feature-server:0.42.0" image

### ISSUE THREAD

**Issue by tchughesiv** [feast-dev/feast#4829]
## Expected Behavior
Feast services should run without issue. 

## Current Behavior
throws an error at startup
```
Traceback (most recent call last):
  File "/usr/local/bin/feast", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/feast/cli.py", line 1098, in serve_registry_command
    store.serve_registry(port, tls_key_path, tls_cert_path)
  File "/usr/local/lib/python3.11/site-packages/feast/feature_store.py", line 1957, in serve_registry
    registry_server.start_server(
  File "/usr/local/lib/python3.11/site-packages/feast/registry_server.py", line 769, in start_server
    init_auth_manager(
  File "/usr/local/lib/python3.11/site-packages/feast/permissions/server/utils.py", line 117, in init_auth_manager
    from feast.permissions.auth.kubernetes_token_parser import (
  File "/usr/local/lib/python3.11/site-packages/feast/permissions/auth/kubernetes_token_parser.py", line 5, in <module>
    from kubernetes import client, config
ModuleNotFoundError: No module named 'kubernetes'
```
## Steps to reproduce
enable kubernetes auth in `feature_store.yaml` -
```yaml
auth:
    type: kubernetes
```

### Specifications

- Version: - 0.42.0
- Platform: container

## Possible Solution
Add kubernetes to pip install in Dockerfile

**Comment by franciscojavierarceo** [comment]
CC @dmartinol @redhatHameed @lokeshrangineni

**Comment by tchughesiv** [comment]
i tried adding the module to the Dockerfile like so, but it didn't help -
```
RUN pip install --no-cache-dir "feast[aws,gcp,snowflake,redis,go,mysql,postgres,opentelemetry,grpcio,kubernetes]"
```

**Comment by tchughesiv** [comment]
interestingly, the resulting image from a `make build-feature-server-dev` works as expected.

**Comment by redhatHameed** [comment]
I don't see that image has kubernetes module`pip list | grep kubernetes`

**Comment by redhatHameed** [comment]
```root@14591aac3fb7:/#  pip list
Package                       Version
----------------------------- --------------
aiobotocore                   2.15.2
aiohappyeyeballs              2.4.4
aiohttp                       3.11.10
aioitertools                  0.12.0
aiosignal                     1.3.1
annotated-types               0.7.0
anyio                         4.7.0
asn1crypto                    1.5.1
attrs                         24.2.0
bigtree                       0.22.3
boto3                         1.35.36
botocore                      1.35.36
cachetools                    5.5.0
certifi                       2024.8.30
cffi                          1.15.1
charset-normalizer            3.4.0
click                         8.1.7
cloudpickle                   3.1.0
colorama                      0.4.6
cryptography                  44.0.0
dask                          2024.12.0
dask-expr                     1.1.20
db-dtypes                     1.3.1
dill                          0.3.9
fastapi                       0.115.6
feast                         0.42.0
filelock                      3.16.1
frozenlist                    1.5.0
fsspec                        2024.9.0
google-api-core               2.23.0
google-auth                   2.36.0
google-cloud-bigquery         3.27.0
google-cloud-bigquery-storage 2.27.0
google-cloud-bigtable         2.27.0
google-cloud-core             2.4.1
google-cloud-datastore        2.20.1
google-cloud-storage          2.19.0
google-crc32c                 1.6.0
google-resumable-media        2.7.2
googleapis-common-protos      1.66.0
greenlet                      3.1.1
grpc-google-iam-v1            0.13.1
grpcio                        1.68.1
grpcio-health-checking        1.62.3
grpcio-reflection             1.62.3
grpcio-status                 1.62.3
gunicorn                      23.0.0
h11                           0.14.0
hiredis                       2.4.0
httptools                     0.6.4
idna                          3.10
importlib_metadata            8.5.0
Jinja2                        3.1.4
jmespath                      1.0.1
jsonschema                    4.23.0
jsonschema-specifications     2024.10.1
locket                        1.0.0
MarkupSafe                    3.0.2
mmh3                          5.0.1
multidict                     6.1.0
mypy                          1.13.0
mypy-extensions               1.0.0
numpy                         1.26.4
packaging                     24.2
pandas                        2.2.3
partd                         1.4.2
pip                           24.3.1
platformdirs                  4.3.6
prometheus_client             0.21.1
propcache                     0.2.1
proto-plus                    1.25.0
protobuf                      4.25.5
psutil                        6.1.0
psycopg                       3.2.3
psycopg-binary                3.2.3
psycopg-pool                  3.2.4
pyarrow                       18.0.0
pyasn1                        0.6.1
pyasn1_modules                0.4.1
pycparser                     2.22
pydantic                      2.10.3
pydantic_core                 2.27.1
Pygments                      2.18.0
PyJWT                         2.10.1
PyMySQL                       1.1.1
pyOpenSSL                     24.3.0
python-dateutil               2.9.0.post0
python-dotenv                 1.0.1
pytz                          2024.2
PyYAML                        6.0.2
redis                         4.6.0
referencing                   0.35.1
requests                      2.32.3
rpds-py                       0.22.3
rsa                           4.9
s3transfer                    0.10.4
setuptools                    65.5.1
six                           1.17.0
sniffio                       1.3.1
snowflake-connector-python    3.12.4
sortedcontainers              2.4.0
SQLAlchemy                    2.0.36
starlette                     0.41.3
tabulate                      0.9.0
tenacity                      8.5.0
toml                          0.10.2
tomlkit                       0.13.2
toolz                         1.0.0
tqdm                          4.67.1
typeguard                     4.4.1
types-PyMySQL                 1.1.0.20241103
typing_extensions             4.12.2
tzdata                        2024.2
urllib3                       2.2.3
uvicorn                       0.32.1
uvicorn-worker                0.2.0
uvloop                        0.21.0
watchfiles                    1.0.0
websockets                    14.1
wheel                         0.45.1
wrapt                         1.17.0
yarl                          1.18.3
zipp                          3.21.0
root@14591aac3fb7:/# pip list | grep kubernetes
```

**Comment by tchughesiv** [comment]
```shell
$ pip install "feast[kubernetes]"==0.42.0 > output
WARNING: feast 0.42.0 does not provide the extra 'kubernetes'
```

**Comment by dmartinol** [comment]
`pip install ".[k8s]"`
